---
# TODO: these should probably be set elsewhere, perhaps becoming mandatory parameters

instances: {}

backends: []
# - name: ...
#   balance: ...
#   healthCheck: ...
#   hostname: ...
#   check_expect: 200|401|403|302|405
#   cookie: ...
#   servers:
#   - ...
