---
- name: Get certificates list
  include_role:
    name: azure_keyvault
    tasks_from: get_secrets_list.yml
  vars:
    curl:
      retries: 0
      delay: 5

- name: Process certificate
  include_tasks: download_single_key_vault_certificate.yml
  vars:
    certificate_name: "{{ item.split('/') | last }}"
  loop: "{{ secrets_list }}"
