---
- name: Create directory for kafka messages
  file:
    dest: "kafka_messages/"
    state: directory
    mode: u=rwx,go=rx

- name: Download key vault certificates
  include_tasks: download_all_key_vault_certificates.yml
  when: azure_kv_name is defined

- name: Recursevly find all certificate files in a folder
  ansible.builtin.find:
    paths: "{{ certs_folder }}"
    patterns: '*.pem'
    recurse: yes
  register: found_certificates

- name: Process certificate
  include_tasks: process_certificate.yml
  vars:
    certificate_name: "{{ item.path.split(certs_folder) | last }}"
  loop: "{{ found_certificates.files }}"
