---
trigger: none

# schedules:
# - cron: "0 0 * * *"
#   displayName: Daily servers upgrade
#   always: true
#   branches:
#     include:
#     - master

variables:
  - template: artifacts.yml
  - name: azure_kv_name
    value: kv-wtg-iris-prod
  - name: username
    value: "WTGOps"
  - name: email
    value: "wtgops@wisetechglobal.com"
  - name: upgrade_files
    value: $(System.DefaultWorkingDirectory)/data/static_backends/cww.yaml
  - name: branch_name
    value: automatic_servers_update

pool: cicd-v2

steps:
  - script: |
      set -euxo pipefail
      pip install -r requirements.txt
    displayName: 'Install requirements'

  # Azure cli and git config taken directly from artifact upgrades pipeline
  - script: |
      set -euxo pipefail
      pip install --pre azure-cli --extra-index-url https://azurecliprod.blob.core.windows.net/edge
      pip install --upgrade azure-core
    displayName: "Upgrade Azure CLI"

  - script: |
      set -euxo pipefail
      az extension add --upgrade --yes --name azure-devops
    displayName: "Add Azure-DevOps extension"

  - script: |
      set -euxo pipefail
      echo $(System.AccessToken) | az devops login
    displayName: "Login via Azure DevOps CLI"

  - script: |
      set -euxo pipefail
      az devops configure --defaults organization=$(System.TeamFoundationCollectionUri) \
        project="$(System.TeamProject)"
    displayName: "Configure defaults for Azure DevOps organisation and project"

  - script: |
      set -euxo pipefail
      git config --global user.name $(username)
      git config --global user.email $(email)
    displayName: "Configure git globals"

  - task: DownloadPipelineArtifact@2
    displayName: 'Download dante artifact'
    inputs:
      buildType: 'specific'
      project: 'InfrastructureAutomation'
      # dante build artifact pipeline Id
      pipeline: 26
      buildVersionToDownload: 'specific'
      buildId: '$(dante_build_id)'
      path: $(Build.SourcesDirectory)

  - task: CopyFiles@2
    displayName: 'Merge artifacts to a single roles folder'
    inputs:
      sourceFolder: iris
      targetFolder: ansible

  - task: AzureKeyVault@2
    displayName: 'Get secrets from Azure KV'
    inputs:
      azureSubscription: 'sc-azuredevops2dante-vaults'
      KeyVaultName: $(azure_kv_name)
      SecretsFilter: secretAppIdDf4b4604e176
      RunAsPreJob: false

  - task: Ansible@0
    displayName: 'Update servers'
    inputs:
      ansibleInterface: 'agentMachine'
      playbookPathOnAgentMachine: 'ansible/update_servers.yaml'
      failOnStdErr: false
      args: >-
        --diff
        -e="azure_kv_name=$(azure_kv_name)"
    env:
      secretAppIdDf4b4604e176: $(secretAppIdDf4b4604e176)

  - script: |
      set -euxo pipefail
      git fetch origin master
      git checkout -b $(branch_name) origin/master
    displayName: Create new branch

  - script: |
      set -euxo pipefail
      if [[ $(echo $(upgrade_files) | xargs git status --porcelain) ]]; then
        git add $(upgrade_files)
        git commit -m "Automated Push of $(branch_name)"
      else
        echo -n "$(date) INFO - There is no difference between commits."
        set +x
        echo "##vso[task.setvariable variable=changed]no"
        exit 0
      fi
      git push -f origin $(branch_name)
      echo -n "$(date) INFO - There is a difference between commits. Attempt to create PR."
      set +x
      echo "##vso[task.setvariable variable=changed]yes"
    displayName: Push Commit

  - script: |
      az repos pr list --source-branch $(branch_name) | jq -e '.[0]'
      if [[ $? -ne 0 ]]; then
        az repos pr create --auto-complete true --repository $(repository) \
        --source-branch $(branch_name) \
        --target-branch master --delete-source-branch true --title "Automated Servers update"
        exit 0
      else
        echo "No PR created as it already exists"
      fi
    condition: and(succeeded(), eq(variables['changed'], 'yes'))
    displayName: Create PR and Set Auto-Complete
