---
# Configuration for Azure DevOps build pipeline
trigger: none

variables:
- template: artifacts.yml
- name: user
  value: dante

stages:
# - stage: Tests_and_lint
#   pool: cicd
#   jobs:
#   - job: Tests_and_lint
#     steps:
#     - script: |
#         set -euxo pipefail
#         pip install -r requirements.txt
#       displayName: 'Install requirements'


- stage: Simulations
  # dependsOn: [Tests_and_lint]
  pool: test-pool
  jobs:
  - job: Simulation
    steps:
    - script: |
        set -euxo pipefail
        pip install -r requirements.txt
      displayName: 'Install requirements'

    - task: Ansible@0
      displayName: 'Test haproxy'
      inputs:
        ansibleInterface: 'agentMachine'
        playbookPathOnAgentMachine: 'ansible/test_haproxy.yml'
        inventoriesAgentMachine: 'file'
        failOnStdErr: false
        args: >-
          -u $(user) --diff
          -e="build_id=$(Build.BuildId)$(System.JobAttempt)"
          -i instances/au1-prod-frontend-1.yml
          -i instances/au2-prod-ceph-1.ym
