---
trigger: none

variables:
  - template: artifacts.yml
  - name: key_vault_name
    value: kv-wtg-iris-prod
  - name: username
    value: "WTGOps"
  - name: email
    value: "wtgops@wisetechglobal.com"

stages:
  - stage: Update_IIS_Data
    pool:
      name: dante
      demands:
        - WTG_DC -equals $(dc)
    jobs:
      - job: Update_IIS_Data
        strategy:
          matrix:
            AU:
              dc: AU2
        steps:
          - checkout: self
            persistCredentials: true

          - script: |
              set -euxo pipefail
              pip install -r requirements.txt
            displayName: 'Install requirements'

          - task: AzureKeyVault@2
            displayName: 'Get secrets from Azure KV'
            inputs:
              azureSubscription: 'sc-azuredevops2dante-vaults'
              KeyVaultName: '$(key_vault_name)'
              SecretsFilter: secretAppIdDf4b4604e176
              RunAsPreJob: false

          - script: |
              set -euxo pipefail
              pip install --pre azure-cli --extra-index-url https://azurecliprod.blob.core.windows.net/edge
              pip install --upgrade azure-core
            displayName: "Upgrade Azure CLI"

          - script: |
              set -euxo pipefail
              az extension add --upgrade --yes --name azure-devops
            displayName: "Add Azure-DevOps extension"

          - script: |
              set -euxo pipefail
              echo $(System.AccessToken) | az devops login
            displayName: "Login via Azure DevOps CLI"

          - script: |
              set -euxo pipefail
              az devops configure --defaults organization=$(System.TeamFoundationCollectionUri) \
                project="$(System.TeamProject)"
            displayName: "Configure defaults for Azure DevOps organisation and project"

          - script: |
              set -euxo pipefail
              git config --global user.name $(username)
              git config --global user.email $(email)
            displayName: "Configure git globals"

          - task: DownloadPipelineArtifact@2
            displayName: 'Download dante artifact'
            inputs:
              buildType: 'specific'
              project: 'InfrastructureAutomation'
              # dante build artifact pipeline Id
              pipeline: 26
              buildVersionToDownload: 'specific'
              buildId: '$(dante_build_id)'
              path: $(Build.SourcesDirectory)

          - task: CopyFiles@2
            displayName: 'Merge artifacts to a single roles folder'
            inputs:
              sourceFolder: iris
              targetFolder: ansible

          - task: Ansible@0
            displayName: 'Colect sites data and Render Dynamic backends'
            inputs:
              ansibleInterface: 'agentMachine'
              playbookPathOnAgentMachine: 'ansible/collect_and_process_sites_data.yml'
              inventoriesAgentMachine: 'file'
              inventoryFileOnAgentMachine: 'data/instances'
              failOnStdErr: false
              args: >-
                --diff
                -e="winrm_password=$(winrm_password)"
                -e="key_vault_name=$(key_vault_name)"
            env:
              secretAppIdDf4b4604e176: $(secretAppIdDf4b4604e176)

          - script: |
              set -euxo pipefail
              git fetch origin create_pr
              git checkout -b automatic_sites_data_upload origin/create_pr
            displayName: Create new branch

          - script: |
              git add data/autogenerated/
              set -euxo pipefail
              CHANGES=$(git diff --name-only origin/create_pr -- data/autogenerated/)
              if [ -n "$CHANGES" ]; then
                git commit -m "Automated Update of sites data"
              else
                echo -n "$(date) INFO - There is no difference between commits."
                set +x
                echo "##vso[task.setvariable variable=changed]no"
                exit 0
              fi
              git push -f origin automatic_sites_data_upload
              echo -n "$(date) INFO - There is a difference between commits. Attempt to create PR."
              set +x
              echo "##vso[task.setvariable variable=changed]yes"
            displayName: Push Commit

          # - script: |
          #     az repos pr list --source-branch automatic_${{ image.name }}_image_upgrade | jq -e '.[0]'
          #     if [[ $? -ne 0 ]]; then
          #       az repos pr create --auto-complete true --repository $(repository) \
          #       --source-branch automatic_${{ image.name }}_image_upgrade \
          #       --target-branch master --delete-source-branch true --title "Automated ${{ image.name }} image update"
          #       exit 0
          #     else
          #       echo "No PR created as it already exists"
          #     fi
          #   condition: and(succeeded(), eq(variables['changed'], 'yes'))
          #   displayName: "${{ image.name }}: Create PR and Set Auto-Complete"

          # - script: |
          #     set -euxo pipefail
          #     git fetch origin master
          #     git pull
          #     git checkout $(Build.SourceBranchName)
          #   displayName: "${{ image.name }}: Switch back to working branch"