---
trigger: none

variables:
  - template: artifacts.yml
  - name: user
    value: dante
  - name: cert_kv_name
    value: kv-wtg-iris-e2open
  - name: key_vault_name
    value: kv-wtg-iris-e2open
  - name: target_dc
    value: DE1

stages:
  - stage: Deploy_Haproxy_E2Open
    pool:
      name: e2open-haproxy
    lockBehavior: sequential
    dependsOn: []
    jobs:
      - deployment: Deploy_Haproxy_E2Open
        environment: iris_e2open_pipeline_lock
        workspace:
          clean: all
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - script: |
                    set -euxo pipefail
                    rm -rf $(Build.SourcesDirectory)/data
                  displayName: 'Remove data directory from checkout'

                - task: InstallSSHKey@0
                  displayName: 'Install an SSH key'
                  inputs:
                    knownHostsEntry: 'StrictHostKeyChecking no'
                    sshKeySecureFile: 'id_rsa_e2open'

                # TODO: Disable wtg.monitoring_agents in IRIS-e2open
                - script: |
                    set -euxo pipefail
                    pip install -r requirements.txt
                  displayName: 'Install requirements'

                - script: |
                    set -euxo pipefail
                    cp ansible/ansible.cfg .
                  displayName: 'Prepare to run playbooks'

                - task: DownloadPipelineArtifact@2
                  displayName: 'Download dante artifact'
                  inputs:
                    buildType: 'specific'
                    project: 'InfrastructureAutomation'
                    # dante build artifact pipeline Id
                    pipeline: 26
                    buildVersionToDownload: 'specific'
                    buildId: '$(dante_build_id)'
                    path: $(Build.SourcesDirectory)

                - task: CopyFiles@2
                  displayName: 'Merge artifacts to a single roles folder'
                  inputs:
                    sourceFolder: iris
                    targetFolder: ansible

                - task: CopyFiles@2
                  displayName: 'Merge e2open to a single roles folder'
                  inputs:
                    sourceFolder: e2open
                    targetFolder: $(Build.SourcesDirectory)
                    overWrite: true

                - task: AzureKeyVault@2
                  displayName: 'Get secrets from Azure KV'
                  inputs:
                    azureSubscription: 'sc-azuredevops2dante-vaults'
                    KeyVaultName: '$(key_vault_name)'
                    SecretsFilter: secretAppIDd47f8828f95e
                    RunAsPreJob: false

                - task: Bash@3
                  displayName: 'Deploy haproxy'
                  inputs:
                    targetType: 'inline'
                    script: |
                      set -euo pipefail
                      exec ansible-playbook \
                        ansible/deploy_haproxy.yml \
                        -i data/instances \
                        -u $(user) --diff \
                        -e="build_id=$(Build.BuildId)$(System.JobAttempt)" \
                        -e="{simulation: false}" \
                        -e="{use_s3: false}" \
                        -e="{enable_dynamic_backends: false}" \
                        -e="{deploy_telegraf: false}" \
                        -e="key_vault_name=$(key_vault_name)" \
                        -e="skip_keepalived_hosts='$(skip_keepalived_hosts)'" \
                        -e="{instance_auto_restart_allowed: $(instance_auto_restart_allowed)}" \
                        -e="target_dc=$(target_dc)"
                  env:
                    secretAppIDd47f8828f95e: $(secretAppIDd47f8828f95e)
                    ANSIBLE_DISPLAY_SKIPPED_HOSTS: $(ansible_display_skipped_hosts)
                    ANSIBLE_DISPLAY_OK_HOSTS: $(ansible_display_ok_hosts)
