---
trigger:
  - master

variables:
  - template: artifacts.yml
  - name: user
    value: dante
  - name: cert_kv_name
    value: kv-wtg-iris-prod
  - name: key_vault_name
    value: kv-wtg-iris-prod

name: "$(Date:yyyyMMdd)$(Rev:.r)_Deploy_to_$(dc)"

parameters:
  - name: matrix
    type: object
    default:
      - target_dc: AU2
        agent_dc: AU2
        agent_hall: A
        s3_host: au2s3-2.wtg.ws
        s3_iris_bucket: s3://au-iscore-iris-prod-1/
        pure_usernames: au-iscore-iris-prod-1-rw
      - target_dc: DE1
        agent_dc: DE1
        agent_hall: A
        s3_host: de1s3-2.wtg.ws
        s3_iris_bucket: s3://de-iscore-iris-prod-1/
        pure_usernames: de-iscore-iris-prod-1-rw
      - target_dc: US2
        agent_dc: US2
        agent_hall: A
        s3_host: us2s3-2.wtg.ws
        s3_iris_bucket: s3://us-iscore-iris-prod-1/
        pure_usernames: us-iscore-iris-prod-1-rw
      - target_dc: CN1
        agent_dc: AU2
        agent_hall: A
        s3_host: au2s3-2.wtg.ws
        s3_iris_bucket: s3://au-iscore-iris-prod-1/
        pure_usernames: au-iscore-iris-prod-1-rw
      - target_dc: SA1
        agent_dc: AU2
        agent_hall: A
        s3_host: au2s3-2.wtg.ws
        s3_iris_bucket: s3://au-iscore-iris-prod-1/
        pure_usernames: au-iscore-iris-prod-1-rw

stages:
  - ${{ each run in parameters.matrix }}:
      - stage: Deploy_Haproxy_${{ run.target_dc }}
        pool:
          name: dante
          demands:
            - WTG_DC -equals ${{ run.agent_dc }}
            - WTG_HALL -equals ${{ run.agent_hall }}
        lockBehavior: sequential
        dependsOn: []
        jobs:
          - deployment: Deploy_Haproxy_${{ run.target_dc }}
            condition: or(eq('${{ run.target_dc }}', variables['dc']), eq(variables['dc'], 'all'))
            environment: iris_${{ run.target_dc }}_pipeline_lock
            workspace:
              clean: all
            strategy:
              runOnce:
                deploy:
                  steps:
                    - checkout: self

                    - task: InstallSSHKey@0
                      displayName: 'Install an SSH key'
                      inputs:
                        knownHostsEntry: 'StrictHostKeyChecking no'
                        sshKeySecureFile: 'id_rsa_dante'

                    - script: |
                        set -euxo pipefail
                        pip install -r requirements.txt
                        EXTRAHEADER="http.https://dev.azure.com/.extraheader"
                        git config --global --unset-all ${EXTRAHEADER} || true
                        git config --global ${EXTRAHEADER} "AUTHORIZATION: bearer $(System.AccessToken)"
                        ansible-galaxy install -r ansible/requirements.yml --force
                      displayName: 'Install requirements'

                    - script: |
                        git config --global --unset-all http.https://dev.azure.com/.extraheader || true
                      displayName: 'Cleanup Git credentials'
                      condition: always()

                    - script: |
                        set -euxo pipefail
                        test "$(Build.SourceBranchName)" = "master"
                        cp ansible/ansible.cfg .
                      displayName: 'Prepare to run playbooks'

                    - task: DownloadPipelineArtifact@2
                      displayName: 'Download dante artifact'
                      inputs:
                        buildType: 'specific'
                        project: 'InfrastructureAutomation'
                        # dante build artifact pipeline Id
                        pipeline: 26
                        buildVersionToDownload: 'specific'
                        buildId: '$(dante_build_id)'
                        path: $(Build.SourcesDirectory)

                    - task: CopyFiles@2
                      displayName: 'Merge artifacts to a single roles folder'
                      inputs:
                        sourceFolder: iris
                        targetFolder: ansible

                    - task: AzureKeyVault@2
                      displayName: 'Get secrets from Azure KV'
                      inputs:
                        azureSubscription: 'sc-azuredevops2dante-vaults'
                        KeyVaultName: '$(key_vault_name)'
                        SecretsFilter: secretAppIdDf4b4604e176
                        RunAsPreJob: false

                    - task: Ansible@0
                      displayName: 'Check and save certificates'
                      inputs:
                        ansibleInterface: 'agentMachine'
                        playbookPathOnAgentMachine: 'ansible/check_and_save_certificates_cms.yml'
                        inventoriesAgentMachine: 'file'
                        inventoryFileOnAgentMachine: 'data/instances'
                        failOnStdErr: false
                        args: >-
                          -u $(user) --diff
                          -e="build_id=$(Build.BuildId)$(System.JobAttempt)"
                          -e="{simulation: false}" -e="azure_kv_name=$(cert_kv_name)"
                          -e="target_dc=${{ run.target_dc }}"
                      env:
                        secretAppIdDf4b4604e176: $(secretAppIdDf4b4604e176)

                    - task: DownloadPipelineArtifact@2
                      displayName: 'Download sqlbilling artifacts for ACL'
                      inputs:
                        buildType: 'specific'
                        project: 'ISOperations'
                        # https://dev.azure.com/WTGOps/ISOperations/_build?definitionId=239
                        pipeline: 239
                        artifact: sqlbilling
                        buildVersionToDownload: 'specific'
                        buildId: '$(sqlbilling_build_id)'
                        path: $(Build.SourcesDirectory)/sqlbilling_acl
                        patterns: 'acl/*.acl'

                    - task: Bash@3
                      displayName: 'Deploy haproxy'
                      inputs:
                        targetType: 'inline'
                        script: |
                          set -euo pipefail
                          exec ansible-playbook \
                            ansible/deploy_haproxy.yml \
                            -i data/instances \
                            -u $(user) --diff \
                            -e="build_id=$(Build.BuildId)$(System.JobAttempt)" \
                            -e="{simulation: false}" \
                            -e="winrm_password=$(winrm_password)" \
                            -e="s3_host=${{ run.s3_host }}" \
                            -e="pure_usernames='${{ run.pure_usernames }}'" \
                            -e="s3_iris_bucket=${{ run.s3_iris_bucket }}" \
                            -e="key_vault_name=$(key_vault_name)" \
                            -e="skip_keepalived_hosts='$(skip_keepalived_hosts)'" \
                            -e="sqlbilling_acl_dir=$(Build.SourcesDirectory)/sqlbilling_acl/acl" \
                            -e="{instance_auto_restart_allowed: $(instance_auto_restart_allowed)}" \
                            -e="{ensure_no_haproxy_changes: $(ensure_no_haproxy_changes)}" \
                            -e="target_dc=${{ run.target_dc }}"
                      env:
                        secretAppIdDf4b4604e176: $(secretAppIdDf4b4604e176)
                        ANSIBLE_DISPLAY_SKIPPED_HOSTS: $(ansible_display_skipped_hosts)
                        ANSIBLE_DISPLAY_OK_HOSTS: $(ansible_display_ok_hosts)

                    - task: Ansible@0
                      displayName: 'Check the instances to be torn down'
                      inputs:
                        ansibleInterface: 'agentMachine'
                        playbookPathOnAgentMachine: 'ansible/teardown_haproxy.yml'
                        inventoriesAgentMachine: 'file'
                        inventoryFileOnAgentMachine: 'data/instances'
                        failOnStdErr: false
                        args: >-
                          -u $(user) --diff
                          -e="{simulation: false}"
                          -e="{instance_teardown_allowed: $(instance_teardown_allowed)}"
                          -e="target_dc=${{ run.target_dc }}"
                      env:
                        secretAppIdDf4b4604e176: $(secretAppIdDf4b4604e176)
