---
trigger: none

variables:
  - template: artifacts.yml
  - name: key_vault_name
    value: kv-wtg-iris-prod

stages:
  - stage: Update_IIS_Data
    pool:
      name: dante
      demands:
        - WTG_DC -equals $(dc)
    jobs:
      - job: Update_IIS_Data
        strategy:
          matrix:
            AU:
              dc: AU2
        steps:
          - script: |
              set -euxo pipefail
              pip install -r requirements.txt
            displayName: 'Install requirements'

          - task: AzureKeyVault@2
            displayName: 'Get secrets from Azure KV'
            inputs:
              azureSubscription: 'sc-azuredevops2dante-vaults'
              KeyVaultName: '$(key_vault_name)'
              SecretsFilter: secretAppIdDf4b4604e176
              RunAsPreJob: false

          - task: Ansible@0
            displayName: 'Check IIS data'
            inputs:
              ansibleInterface: 'agentMachine'
              playbookPathOnAgentMachine: 'ansible/collect_and_process_sites_data.yml'
              inventoriesAgentMachine: 'file'
              inventoryFileOnAgentMachine: 'data/instances'
              failOnStdErr: false
              args: >-
                --diff
                -e="winrm_password=$(winrm_password)"
                -e="key_vault_name=$(key_vault_name)"
            env:
              secretAppIdDf4b4604e176: $(secretAppIdDf4b4604e176)
