---
# Configuration for Azure DevOps build pipeline
trigger: none

variables:
  - template: artifacts.yml
  - name: user
    value: dante
  - name: azure_kv_name
    value: kv-wtg-test
  - name: mgmt_keyvault_name
    value: kv-wtg-dante-sim

stages:
  # - stage: Tests_and_lint
  #   pool: cicd
  #   jobs:
  #     - job: Tests_and_lint
  #       steps:
  #         - script: |
  #             set -euxo pipefail
  #             pip install -r requirements.txt
  #           displayName: 'Install requirements'

  #         - script: |
  #             set -euxo pipefail
  #             pytest
  #           displayName: 'Python tests'

  #         - task: PublishTestResults@2
  #           condition: succeededOrFailed()
  #           inputs:
  #             testResultsFiles: 'reports/nosetests.xml'

  #         - script: |
  #             set -euxo pipefail
  #             pylint --rcfile=setup.cfg tests/ ansible/roles/collect_sites/files/*.py
  #           displayName: 'Python lint'
  #           condition: succeededOrFailed()

  #         - script: |
  #             set -euxo pipefail
  #             safety check --full-report -i 42923 -i 42926
  #           # Ignored reports:
  #           #   - 42923,42926 - CVE-2021-3532 and CVE-2021-3533 - Results of
  #           #   Ansible async tasks can be leaked to malicious non-privileged users
  #           #   on the target machine, under some circumstances. However, we do not
  #           #   have any async tasks in this repo.
  #           displayName: 'Python Safety vulnerability check'
  #           condition: succeededOrFailed()

  #         - script: |
  #             set -euxo pipefail
  #             yamllint -s .
  #           displayName: 'YAML lint'
  #           condition: succeededOrFailed()

  #         - script: |
  #             set -euxo pipefail
  #             bandit -r .
  #           displayName: 'Bandit security check'
  #           condition: succeededOrFailed()

  #         - script: |
  #             set -euxo pipefail
  #             ansible-lint $(find ansible -iname '*.y*ml')
  #           displayName: 'Ansible lint'
  #           condition: succeededOrFailed()

  - stage: Simulations
    # dependsOn: [Tests_and_lint]
    pool: test-pool
    jobs:
      - job: Simulation
        steps:
          - task: AzureKeyVault@2
            displayName: 'Get secret to authenticate to key vault from ansible'
            inputs:
              azureSubscription: 'sc-azuredevops2dante-vaults'
              KeyVaultName: kv-wtg-dante-sim
              SecretsFilter: secretAppIdDf4b4604e176

          - script: |
              set -euxo pipefail
              pip install -r requirements.txt
            displayName: 'Install requirements'

          - task: DownloadPipelineArtifact@2
            displayName: 'Download dante artifact'
            inputs:
              buildType: 'specific'
              project: 'InfrastructureAutomation'
              # dante build artifact pipeline Id
              pipeline: 26
              buildVersionToDownload: 'specific'
              buildId: '$(dante_build_id)'
              path: $(Build.SourcesDirectory)

          - task: CopyFiles@2
            displayName: 'Merge artifacts to a single roles folder'
            inputs:
              sourceFolder: nested_virt
              targetFolder: ansible

          - task: InstallSSHKey@0
            displayName: 'Install an SSH key'
            inputs:
              knownHostsEntry: 'StrictHostKeyChecking no'
              sshKeySecureFile: 'id_rsa'

          - task: Ansible@0
            displayName: 'Check and save certificates'
            inputs:
              ansibleInterface: 'agentMachine'
              playbookPathOnAgentMachine: 'ansible/check_and_save_certificates.yml'
              inventoriesAgentMachine: 'file'
              inventoryFileOnAgentMachine: 'instances'
              failOnStdErr: false
              args: >-
                -u $(user) --diff
                -e="build_id=$(Build.BuildId)$(System.JobAttempt)"
                -e="simulation=true" -e="azure_kv_name=$(azure_kv_name)"
            env:
              secretAppIdDf4b4604e176: $(secretAppIdDf4b4604e176)

          - task: Ansible@0
            displayName: 'Test haproxy'
            inputs:
              ansibleInterface: 'agentMachine'
              playbookPathOnAgentMachine: 'ansible/test_haproxy.yml'
              inventoriesAgentMachine: 'file'
              inventoryFileOnAgentMachine: 'instances'
              failOnStdErr: false
              args: >-
                -u $(user) --diff
                -e="build_id=$(Build.BuildId)$(System.JobAttempt)"
                -e="simulation=true" -e="azure_kv_name=$(mgmt_keyvault_name)"
            env:
              secretAppIdDf4b4604e176: $(secretAppIdDf4b4604e176)

          - task: Ansible@0
            displayName: 'Cleanup'
            inputs:
              ansibleInterface: 'agentMachine'
              playbookPathOnAgentMachine: 'ansible/simulation_cleanup.yaml'
              failOnStdErr: false
              args: >-
                -u $(user) --diff -e="pool=/mnt/storage/test_pool" -e="iso_path=/mnt/storage/iso"
            condition: always()
