---
# Configuration for Azure DevOps build pipeline
trigger: none

variables:
  - template: artifacts.yml
  - name: user
    value: dante
  - name: azure_kv_name
    value: kv-wtg-iris-prod
  - name: mgmt_keyvault_name
    value: kv-wtg-dante-sim
  - name: s3_host
    value: au2s3-2.wtg.ws
  - name: pure_usernames
    value: au-iscore-iris-prod-1-rw
  - name: s3_iris_bucket
    value: s3://au-iscore-iris-prod-1/
  - name: use_cicd_pool
    value: true
  - name: hall
    value: A
  - name: forks_per_agent
    value: 8

stages:
  - stage: Simulations
    pool: cicd-v2
    jobs:
      - job: Simulation
        steps:
          - checkout: self

          - task: AzureKeyVault@2
            displayName: 'Get secret to authenticate to key vault from ansible'
            inputs:
              azureSubscription: 'sc-azuredevops2dante-vaults'
              KeyVaultName: kv-wtg-dante-sim
              SecretsFilter: secretAppIdDf4b4604e176

          - script: |
              set -euxo pipefail
              pip install -r requirements.txt
            displayName: 'Install requirements'

          - task: DownloadPipelineArtifact@2
            displayName: 'Download Virgil inventories'
            inputs:
              buildType: 'specific'
              project: 'InfrastructureAutomation'
              # virgil pipeline Id
              pipeline: 4
              artifact: inventories
              buildVersionToDownload: 'specific'
              buildId: '$(virgil_build_id)'
              path: $(Build.SourcesDirectory)/inventories
              patterns: all_ssh_authorized_keys

          - task: DownloadPipelineArtifact@2
            displayName: 'Download dante artifact'
            inputs:
              buildType: 'specific'
              project: 'InfrastructureAutomation'
              # dante build artifact pipeline Id
              pipeline: 26
              buildVersionToDownload: 'specific'
              buildId: '$(dante_build_id)'
              path: $(Build.SourcesDirectory)

          - task: CopyFiles@2
            displayName: 'Merge artifacts to a single roles folder'
            inputs:
              sourceFolder: iris
              targetFolder: ansible

          - script: |
              set -euxo pipefail
              cp ansible/ansible.cfg .
              mkdir ansible/play_build_qcow2
              mv ansible/download_files_for_simulation.yaml ansible/play_build_qcow2/download_files_for_simulation.yaml
              cp -r ansible/group_vars ansible/play_build_qcow2
            displayName: 'Prepare to run playbooks'

          - task: InstallSSHKey@0
            displayName: 'Install an SSH key'
            inputs:
              knownHostsEntry: 'StrictHostKeyChecking no'
              sshKeySecureFile: 'id_rsa'

          - task: Ansible@0
            displayName: 'Calculate simulation host to use'
            inputs:
              ansibleInterface: 'agentMachine'
              playbookPathOnAgentMachine: 'ansible/calculate_available_host.yaml'
              failOnStdErr: false
              args: >-
                -u $(user) --diff -e="simulation_hosts=$(simulation_hosts)" -e="username=$(Build.QueuedBy)"
                -e="build_id=$(Build.BuildId)"

          - task: Ansible@0
            displayName: 'Deploy hypervisor'
            inputs:
              ansibleInterface: 'agentMachine'
              playbookPathOnAgentMachine: 'ansible/simulation_setup_circle1.yaml'
              inventoriesAgentMachine: 'file'
              inventoryFileOnAgentMachine: 'data/instances'
              failOnStdErr: false
              args: >-
                -u $(user) --diff -e="pool=/mnt/data1/test_pool"
                -e="apt_mirror=$(apt_mirror)"
                -e="@ansible/hypervisor.yaml" -e="@ansible/build_id.yaml"
                -e="{use_cicd_pool: $(use_cicd_pool)}"
                -e="{config_ssh_for_testing: false}"
                -e="{config_proxy_for_testing: true}"
                -e="key_vault_name=$(mgmt_keyvault_name)"
                -e="cpu=$(cpu)" -e="ram=$(ram)"
                -e="s3_host=$(s3_host)"
                -e="skip_configure_firewall=True"
                -e="apt_mirror=$(apt_mirror)"
            env:
              secretAppIdDf4b4604e176: $(secretAppIdDf4b4604e176)

          - task: Ansible@0
            displayName: 'Download required qcow2 and ISO'
            inputs:
              ansibleInterface: 'agentMachine'
              playbookPathOnAgentMachine: 'ansible/play_build_qcow2/download_files_for_simulation.yaml'
              failOnStdErr: false
              args: >-
                -u $(user) --diff
                -e="@ansible/hypervisor.yaml"
                -e="s3_host=$(s3_host)"
                -e="key_vault_name=$(mgmt_keyvault_name)"
            env:
              secretAppIdDf4b4604e176: $(secretAppIdDf4b4604e176)

          - task: Ansible@0
            displayName: 'Check and save certificates'
            inputs:
              ansibleInterface: 'agentMachine'
              playbookPathOnAgentMachine: 'ansible/check_and_save_certificates_cms.yml'
              inventoriesAgentMachine: 'file'
              inventoryFileOnAgentMachine: 'data/instances'
              failOnStdErr: false
              args: >-
                -u $(user) --diff
                -e="build_id=$(Build.BuildId)$(System.JobAttempt)"
                -e="{simulation: true}" -e="azure_kv_name=$(azure_kv_name)"
                -e="target_dc=$(simulation_dc)"
            env:
              secretAppIdDf4b4604e176: $(secretAppIdDf4b4604e176)

          - task: DownloadPipelineArtifact@2
            displayName: 'Download sqlbilling artifacts for ACL'
            inputs:
              buildType: 'specific'
              project: 'ISOperations'
              # https://dev.azure.com/WTGOps/ISOperations/_build?definitionId=239
              pipeline: 239
              artifact: sqlbilling
              buildVersionToDownload: 'specific'
              buildId: '$(sqlbilling_build_id)'
              path: $(Build.SourcesDirectory)/sqlbilling_acl
              patterns: 'acl/*.acl'

          - task: Ansible@0
            displayName: 'Test haproxy'
            inputs:
              ansibleInterface: 'agentMachine'
              playbookPathOnAgentMachine: 'ansible/test_haproxy.yml'
              inventoriesAgentMachine: 'file'
              inventoryFileOnAgentMachine: 'data/instances'
              failOnStdErr: false
              args: >-
                -u $(user) --diff
                --forks $(forks_per_agent)
                -e="build_id=$(Build.BuildId)$(System.JobAttempt)"
                -e="{simulation: true}" -e="azure_kv_name=$(azure_kv_name)"
                -e="{instance_auto_restart_allowed: $(instance_auto_restart_allowed)}"
                -e="s3_host=$(s3_host)"
                -e="s3_iris_bucket=$(s3_iris_bucket)"
                -e="s3_proxy_host=192.168.255.254" -e="s3_proxy_port=3128"
                -e="target_dc=$(simulation_dc)"
                -e="sqlbilling_acl_dir=$(Build.SourcesDirectory)/sqlbilling_acl/acl"
                -e="@ansible/hypervisor.yaml"
                -e="pure_usernames='$(pure_usernames)'"
                -e="{use_cicd_pool: $(use_cicd_pool)}"
                -e="apt_mirror=$(apt_mirror)"
            env:
              secretAppIdDf4b4604e176: $(secretAppIdDf4b4604e176)

          - task: Ansible@0
            displayName: 'Unregister nodes'
            inputs:
              ansibleInterface: 'agentMachine'
              playbookPathOnAgentMachine: 'ansible/unregister_nodes.yaml'
              inventoriesAgentMachine: 'file'
              inventoryFileOnAgentMachine: 'data/instances'
              failOnStdErr: false
              args: >-
                -u $(user) --diff
                -e="build_id=$(Build.BuildId)$(System.JobAttempt)"
                -e="{simulation: true}" -e="azure_kv_name=$(mgmt_keyvault_name)"
                -e="target_dc=$(simulation_dc)"
            env:
              secretAppIdDf4b4604e176: $(secretAppIdDf4b4604e176)
            condition: always()
