---
- name: Calculate individual instance facts
  vars:
    frontend_names:
      http: l7Frontend
      tcp: l4Frontend
    path_prefix: /mnt/data1/containers
  set_fact:
    container_name: "iris_{{ inventory_hostname }}"
    individual_instance_dir: "{{ path_prefix }}/iris_{{ inventory_hostname }}"
    delay_restart_marker: >-
      {{ path_prefix }}/iris_{{ inventory_hostname }}/DELAY_RESTART-{{ ansible_date_time.iso8601 }}
    user: "{{ hostvars[machine_name].haproxy_user }}"
    subuser: "{{ hostvars[machine_name].haproxy_subuser }}"
    frontend_name: "{{ frontend_names[defaults.mode] }}"

- name: Populate servers data variable for individual instance
  set_fact:
    servers_data: "{{ hostvars['localhost'].complete_iis_data.clustered_instances[clustered_instance_name] }}"
  when:
    - "'complete_iis_data' in hostvars['localhost']"
    - "clustered_instance_name in hostvars['localhost'].complete_iis_data.clustered_instances"

- name: Populate dynamic backends variable for individual instance
  set_fact:
    dynamic_backends: "{{ dynamic_backends | default({}) | combine(item.value.websites_list) }}"
  loop: "{{ servers_data | dict2items }}"
  when:
    - "'complete_iis_data' in hostvars['localhost']"
    - "clustered_instance_name in hostvars['localhost'].complete_iis_data.clustered_instances"
