---
- name: Set container engine
  include_role:
    name: container_runner
    tasks_from: define_engine.yml

- name: "Get list of containers"
  command: >-
    {{ engine }} ps -a
  changed_when: false
  become: yes
  register: container_list

- name: Dump out list of containers
  debug:
    var: container_list

- name: Get logs for container
  command: >-
    {{ engine }} logs iris_{{ inventory_hostname }}
  changed_when: false
  become: yes
  register: container_logs

- name: Dump out logs of container
  debug:
    var: container_logs

# - name: Retrieve the stats page
#   uri:
#     url: http://{{ ansible_host }}:{{ stats.ports.web }}/;json
#     use_proxy: no
#   register: stats_page

# - name: Convert stats
#   set_fact:
#     stats: >-
#       [
#         {% for row in stats_page.json %}
#           {
#             {% for col in row %}
#               {{ "{!r}".format(col['field']['name']) }}: {{ "{!r}".format(col['value']['value']) }},
#             {% endfor %}
#           },
#         {% endfor %}
#       ]

# - name: Dump out the stats
#   debug:
#     var: stats

# TODO: Disabled since adding backends
# - name: Check stats row counts
#   vars:
#     counts: >-
#       {
#         {% for svname in stats | map(attribute='svname') | unique %}
#           "{{ svname }}": {{ stats | selectattr('svname', 'eq', svname) | count }},
#         {% endfor %}
#       }
#     expected_counts:
#       BACKEND: 2  # TODO make this a formula or a range
#       FRONTEND: 2
#       # TODO add the relevant formula or range for SERVER
#   assert:
#     that: counts == expected_counts
#     quiet: "{{ counts == expected_counts }}"
#     fail_msg: >-
#       {% for svname in counts | list | union(expected_counts | list) | unique -%}
#       {% if counts[svname] | default(0) != expected_counts[svname] | default(0) -%}
#       There are {{ counts[svname] | default(0) }} {{ svname | lower }}s
#       ({{ stats | selectattr('svname', 'eq', svname) | map(attribute='pxname') | join(', ') }});
#       expected {{ expected_counts[svname] | default(0) }}.
#       {% endif -%}
#       {% endfor -%}

# TODO: Disabled due to backends giving "server unreachable" error. This is expected in simulation
# - name: Check the statuses in the stats
#   vars:
#     expected_status:
#       FRONTEND: OPEN
#       BACKEND: UP
#     description: "{{ row.pxname }} {{ row.mode }} {{ row.svname | lower }}"
#   assert:
#     that: row.status == expected_status[row.svname]
#     quiet: "{{ row.status == expected_status[row.svname] }}"
#     fail_msg: >-
#         Expected status {{ expected_status[row.svname] }}
#         but {{ description }} is {{ row.status }}
#   loop: "{{ stats }}"
#   loop_control:
#     label: "{{ description }}"
#     loop_var: row

# TODO more checks to come
