---
- name: Copy sorry pages to destination
  copy:
    src: "../static_backends/sorry_pages/{{ item.file }}"
    dest: "{{ individual_instance_dir }}/etc/sorry_pages/"
    mode: a=r
    owner: "{{ user.uid }}"
    group: "{{ user.group }}"
  become: yes
  loop: "{{ sorry_pages_list }}"
