---
- name: Check the instance_auto_restart_allowed parameter
  vars:
    valid_values:
      - true
      - false
  assert:
    that: instance_auto_restart_allowed in valid_values
    fail_msg: >-
      Expected instance_auto_restart_allowed to be one of {{ valid_values }},
      got {{ instance_auto_restart_allowed | default('UNDEFINED') }}

- name: Calculate and populate individual instance facts
  include_tasks: calculations.yml

- name: Create directory {{ item }}
  file:
    dest: "{{ individual_instance_dir }}/{{ item.path }}"
    state: directory
    mode: "{{ item.mode }}"
    owner: "{{ subuser.subuid }}"
    group: "{{ subuser.subgid }}"
  become: yes
  loop:
    - path: ''
      mode: a=rx
    - path: etc/certs
      mode: u=rx,go=
    - path: etc/sorry_pages
      mode: a=rx
    - path: run
      mode: u=rwx,go=

- name: Copy sorry pages to destination
  include_tasks: copy_sorry_pages.yml
  vars:
    sorry_pages_list: "{{ backend_item.value.sorry_pages }}"
  when: "'sorry_pages' in backend_item.value"
  loop: "{{ static_backends | dict2items }}"
  loop_control:
    loop_var: backend_item

- name: Create socket and global-state files
  file:
    path: "{{ individual_instance_dir }}/run/{{ item }}"
    state: touch
    mode: u=rw,go=r
    owner: "{{ subuser.subuid }}"
    group: "{{ subuser.subgid }}"
  loop:
    - global-state
    - haproxy.sock
  become: yes

- name: Check if container exists
  vars:
    name: "{{ container_name }}"
  include_role:
    name: container_runner
    tasks_from: check_container_exists.yml

- name: Template out and validate the haproxy config
  when: container_exists
  block:
    - name: Template out and validate the haproxy config
      vars:
        container_engine: "{{ 'podman' if (ansible_facts['os_family'] | lower == 'redhat') else 'docker' }}"
      template:
        src: haproxy.cfg.j2
        dest: "{{ individual_instance_dir }}/etc/{{ clustered_instance_name }}.cfg"
        mode: u=r,go=
        owner: "{{ subuser.subuid }}"
        group: "{{ subuser.subgid }}"
        validate: >-
          bash -c
          'cp -p %s {{ individual_instance_dir }}/etc/{{ clustered_instance_name }}.cfg.tmp
          && {{ container_engine }} exec {{ container_name }} /usr/local/sbin/haproxy
          -c -f /etc/haproxy/{{ clustered_instance_name }}.cfg.tmp'
      become: yes
      register: config_with_container

  always:
    - name: Delete the temporary file
      file:
        path: "{{ individual_instance_dir }}/etc/{{ clustered_instance_name }}.cfg.tmp"
        state: absent
      become: yes

- name: Template out the haproxy config
  template:
    src: haproxy.cfg.j2
    dest: "{{ individual_instance_dir }}/etc/{{ clustered_instance_name }}.cfg"
    mode: u=r,go=
    owner: "{{ subuser.subuid }}"
    group: "{{ subuser.subgid }}"
  become: yes
  register: config_without_container
  when: not container_exists

- name: Set haproxy_config_changed
  set_fact:
    haproxy_config_changed: "{{ config_with_container.changed or config_without_container.changed }}"

- name: Template out the sorry page
  template:
    src: sorry.http.j2
    dest: "{{ individual_instance_dir }}/etc/sorry.http"
    mode: u=r,go=
    owner: "{{ subuser.subuid }}"
    group: "{{ subuser.subgid }}"
  become: yes
  # TODO: validate
  register: sorry_page

- name: Copy certificates for individual instance
  copy:
    src: "certificates/{{ item }}.pem"
    dest: "{{ individual_instance_dir }}/etc/certs/"
    mode: ug=r,o=
    owner: "{{ subuser.subuid }}"
    group: "{{ subuser.subgid }}"
  become: yes
  loop: "{{ certificates | default([]) }}"
  no_log: true
  register: copy_certificates

- name: Template out the apparmor profile
  template:
    src: apparmor_profile.j2
    dest: "{{ individual_instance_dir }}/apparmor_profile"
    mode: u=r,go=
    owner: root
    group: root
    validate: apparmor_parser -Q %s
  become: yes
  register: apparmor_profile_config

- name: Check if apparmor profile is loaded
  command: apparmor_status --json
  become: yes
  changed_when: no
  register: apparmor_status
  when: apparmor_profile_config is not changed

- name: Immediately load apparmor profile
  command: "apparmor_parser -r -W {{ individual_instance_dir }}/apparmor_profile"
  become: yes
  changed_when: yes
  when: >-  # noqa: no-handler
    apparmor_profile_config is changed
    or container_name not in (apparmor_status.stdout | from_json).profiles

- name: Deploy the haproxy container
  include_role:
    name: container_runner
  vars:
    name: "{{ container_name }}"
    workload: deployment
    image: "wtgopstools.azurecr.io/dante/haproxy:{{ container.haproxy_version }}-{{ container.haproxy_os }}"
    startup_command: >-
      -f /etc/haproxy/{{ clustered_instance_name }}.cfg
    restart: "{{ false if instance_auto_restart_allowed else 'never' }}"  # 'false' means restart if needed
    volumes:
      - "{{ individual_instance_dir }}/etc:/etc/haproxy:z"
      - "{{ individual_instance_dir }}/run:/var/run/haproxy:z"
    net_host: no
    ports: >-
      [
        {% for host_port, container_port in docker_port_map.items() | sort %}
        '{{ host_port }}:{{ container_port }}',
        {% endfor %}
      ]
    apparmor_profile: "{{ container_name }}"
    container_user: "{{ user.uid }}:{{ user.group }}"
    container_dir: "{{ individual_instance_dir }}"
    resources:  # TODO review, probably make configurable
      production:
        cpu: 1000m
        memory: 1000Mi
      simulation:
        cpu: 200m
        memory: 100Mi

- name: Generate delay restart marker
  template:
    src: delay_restart.j2
    dest: "{{ delay_restart_marker }}"
    mode: a=r
  become: yes
  when:
    - need_restart
    - not instance_auto_restart_allowed

- name: Delete old delay restart markers after restarted
  when:
    - need_restart
    - instance_auto_restart_allowed
  block:
    - name: Find all delay restart markers
      find:
        paths: "{{ individual_instance_dir }}"
        patterns: "DELAY_RESTART-*"
      register: files_to_delete

    - name: Delete files
      file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ files_to_delete.files }}"

- name: Save Global state to allow faster reloads
  shell:
    cmd: |
      set -o pipefail
      echo 'show servers state' \
      | nc -U {{ individual_instance_dir }}/run/haproxy.sock \
      > {{ individual_instance_dir }}/run/global-state
    executable: /bin/bash
  become: yes
  changed_when: true
  when:
    - container_exists
    - haproxy_config_changed

- name: Update server states file
  include_tasks: update_states_file.yml
  vars:
    cfg_file: "{{ individual_instance_dir }}/etc/{{ clustered_instance_name }}.cfg"
    states_file: "{{ individual_instance_dir }}/run/global-state"
  when:
    - container_exists
    - haproxy_config_changed

- name: Reload haproxy
  # This cannot be a handler as `include_role` is not supported in handlers
  vars:
    name: "{{ container_name }}"
    signal: HUP
  include_role:
    name: container_runner
    tasks_from: send_signal.yml
  when:
    - container_exists
    - haproxy_config_changed or sorry_page.changed or copy_certificates.changed  # noqa: no-handler
