---
- name: Check the instance_auto_restart_allowed parameter
  vars:
    valid_values:
      - true
      - false
  assert:
    that: instance_auto_restart_allowed in valid_values
    fail_msg: >-
      Expected instance_auto_restart_allowed to be one of {{ valid_values }},
      got {{ instance_auto_restart_allowed | default('UNDEFINED') }}

- name: Calculate and populate individual instance facts
  include_tasks: calculations.yml

- name: Create instance directories
  file:
    dest: "{{ individual_instance_dir }}/{{ item.path }}"
    state: directory
    mode: "{{ item.mode }}"
    owner: "{{ subuser.subuid }}"
    group: "{{ subuser.subgid }}"
  become: yes
  loop:
    - path: ''
      mode: a=rx
    - path: etc/certs
      mode: u=rx,go=
    - path: etc/sorry_pages
      mode: a=rx
    - path: run
      mode: u=rwx,go=

- name: Copy sorry pages to destination
  include_tasks: copy_sorry_pages.yml
  vars:
    sorry_pages_list: "{{ backend_item.value.sorry_pages }}"
  when: "'sorry_pages' in backend_item.value"
  loop: "{{ static_backends | dict2items }}"
  loop_control:
    loop_var: backend_item

- name: Create socket and global-state files
  file:
    path: "{{ individual_instance_dir }}/run/{{ item }}"
    state: touch
    mode: u=rw,go=r
    owner: "{{ subuser.subuid }}"
    group: "{{ subuser.subgid }}"
  loop:
    - global-state
    - haproxy.sock
  become: yes

- name: Template out the sorry page
  template:
    src: sorry.http.j2
    dest: "{{ individual_instance_dir }}/etc/sorry.http"
    mode: u=r,go=
    owner: "{{ subuser.subuid }}"
    group: "{{ subuser.subgid }}"
  become: yes
  # TODO: validate
  register: sorry_page

- name: Find all existing certificate files
  find:
    paths: "{{ individual_instance_dir }}/etc/certs/"
    patterns: "*.pem"
    recurse: no
  become: yes
  register: existing_pem_certs

- name: Identify certificates removed from the config
  set_fact:
    delete_certs: >-
      {{ existing_pem_certs.files | map(attribute='path') | map('basename')
      | map('regex_replace', '\.pem$', '') | list | difference(certificates) }}

- name: Delete certificates removed from the config
  file:
    path: "{{ individual_instance_dir }}/etc/certs/{{ item }}.pem"
    state: absent
  become: yes
  loop: "{{ delete_certs }}"
  when: delete_certs | length > 0

- name: Copy certificates for individual instance
  copy:
    src: "certificates/{{ item }}.pem"
    dest: "{{ individual_instance_dir }}/etc/certs/"
    mode: ug=r,o=
    owner: "{{ subuser.subuid }}"
    group: "{{ subuser.subgid }}"
  become: yes
  loop: "{{ certificates | default([]) }}"
  no_log: true
  register: copy_certificates
  when: (not simulation) or (check_all_certs | default(true))

- name: Copy certificates directory in simulation environment
  copy:
    src: "certificates/"
    dest: "{{ individual_instance_dir }}/etc/certs/"
    mode: ug=r,o=
    owner: "{{ subuser.subuid }}"
    group: "{{ subuser.subgid }}"
  become: yes
  no_log: true
  register: copy_certificates
  when:
    - simulation
    - not(check_all_certs | default(true))

- name: Copy sqlbilling acl files for individual instance
  copy:
    src: "{{ sqlbilling_acl_dir }}/{{ item.file }}"
    dest: "{{ individual_instance_dir }}/etc/"
    mode: ug=r,o=
    owner: "{{ subuser.subuid }}"
    group: "{{ subuser.subgid }}"
  become: yes
  loop: "{{ sqlbilling_acl }}"
  register: copy_sqlbillings
  when: sqlbilling_acl | default([]) | length > 0

- name: Setup apparmor
  when: "virgil_os_variant == 'ubuntu'"  # TODO: check if some config is required for RHEL
  block:
    - name: Copy apparmor_profile to target folder
      copy:
        src: apparmor_profile
        dest: "/etc/apparmor.d/apparmor_profile"
        mode: u=r,go=
        owner: root
        group: root
        validate: apparmor_parser -Q %s
      become: yes
      register: apparmor_profile_config

    - name: Check if apparmor profile is loaded
      command: apparmor_status --json
      become: yes
      changed_when: no
      register: apparmor_status
      when: apparmor_profile_config is not changed

    - name: Immediately load apparmor profile
      command: "apparmor_parser -r -W /etc/apparmor.d/apparmor_profile"
      become: yes
      changed_when: yes
      when: >-  # noqa: no-handler
        apparmor_profile_config is changed
        or container_name not in (apparmor_status.stdout | from_json).profiles

- name: Set container user for Ubuntu
  when: "virgil_os_variant == 'ubuntu'"
  set_fact:
    haproxy_container_user: "{{ user.uid }}"
    haproxy_container_group: "{{ user.group }}"

# We can set actual container user when running podman
- name: Set container user for RHEL
  when: "virgil_os_variant == 'rhel'"
  set_fact:
    haproxy_container_user: "{{ subuser.subuid }}"
    haproxy_container_group: "{{ subuser.subuid }}"

- name: Template out the test haproxy config
  template:
    src: haproxy.cfg.j2
    dest: "{{ individual_instance_dir }}/etc/{{ clustered_instance_name }}.cfg.test"
    mode: u=r,go=
    owner: "{{ subuser.subuid }}"
    group: "{{ subuser.subgid }}"
  become: yes
  register: haproxy_config

- name: Fetch the dumped config
  fetch:
    src: "{{ individual_instance_dir }}/etc/{{ clustered_instance_name }}.cfg.test"
    dest: "../generated_configs/{{ target_dc }}/{{ inventory_hostname }}.cfg"
    flat: true
    fail_on_missing: false
  become: yes
  failed_when: false
  when:
    - simulation
    - enable_dump_configs | default(false)

- name: Validate the haproxy test configuration file  # noqa no-handler
  include_role:
    name: container_runner
    tasks_from: once_off_job.yml
  vars:
    job_name: "validate-{{ container_name }}"
    image: "wtgopstools.azurecr.io/dante/haproxy:{{ container.haproxy_image_tag }}"
    volumes:
      - "{{ individual_instance_dir }}/etc:/etc/haproxy:z"
    startup_command: /usr/local/sbin/haproxy
    startup_args:
      - -c
      - -f
      - /etc/haproxy/{{ clustered_instance_name }}.cfg.test
    container_user: "{{ haproxy_container_user }}:{{ haproxy_container_group }}"
  when: haproxy_config.changed

- name: Copy validated configuration file  # noqa no-handler
  copy:
    src: "{{ individual_instance_dir }}/etc/{{ clustered_instance_name }}.cfg.test"
    dest: "{{ individual_instance_dir }}/etc/{{ clustered_instance_name }}.cfg"
    remote_src: yes
    mode: u=r,go=
    owner: "{{ subuser.subuid }}"
    group: "{{ subuser.subgid }}"
  become: yes
  when: haproxy_config.changed

- name: Deploy the haproxy container (one at a time)
  block:
    - name: Wait until docker pull lock file is absent
      wait_for:
        path: "{{ docker_pull_lock }}"
        state: absent
        timeout: 180

    - name: Create docker pull lock file
      file:
        path: "{{ docker_pull_lock }}"
        state: touch
        mode: a=rw

    - name: Deploy the haproxy container
      include_role:
        name: container_runner
      vars:
        name: "{{ container_name }}"
        workload: deployment
        image: "wtgopstools.azurecr.io/dante/haproxy:{{ container.haproxy_image_tag }}"
        startup_command: >-
          -f /etc/haproxy/{{ clustered_instance_name }}.cfg
        restart: "{{ false if instance_auto_restart_allowed else 'never' }}"  # 'false' means restart if needed
        volumes:
          - "{{ individual_instance_dir }}/etc:/etc/haproxy:z"
          - "{{ individual_instance_dir }}/run:/var/run/haproxy:z"
        net_host: no
        ports: >-
          {%- set result = [] -%}
          {%- for host_port, container_port in docker_port_map.items() | sort -%}
          {%-   set _ = result.append(host_port ~ ':' ~ container_port) -%}
          {%- endfor -%}
          {{ result }}
        apparmor_profile: "{{ 'wtg_iris' if (virgil_os_variant == 'ubuntu') else '' }}"
        container_user: "{{ haproxy_container_user }}:{{ haproxy_container_group }}"
        container_dir: "{{ individual_instance_dir }}"
        resources: "{{ container.resources }}"
  always:
    - name: Remove docker pull lock file
      file:
        state: absent
        path: "{{ docker_pull_lock }}"

- name: Reset container running fact
  set_fact:
    container_running: false

- name: Wait for container to come up
  include_tasks: wait_container_up.yml
  when: not container_running
  loop: "{{ range(0, 10) | list }}"

- name: Assert that container is running
  assert:
    that: container_running
    fail_msg: "Container is not running."

- name: Generate delay restart marker
  template:
    src: delay_restart.j2
    dest: "{{ individual_instance_dir }}/DELAY_RESTART-{{ ansible_date_time.iso8601 }}"
    mode: a=r
  become: yes
  when:
    - need_restart
    - not instance_auto_restart_allowed

- name: Delete old delay restart markers after restarted
  when:
    - need_restart
    - instance_auto_restart_allowed
  block:
    - name: Find all delay restart markers
      find:
        paths: "{{ individual_instance_dir }}"
        patterns: "DELAY_RESTART-*"
      register: files_to_delete

    - name: Delete files
      file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ files_to_delete.files }}"

- name: Save Global state to allow faster reloads  # noqa no-handler
  shell:
    cmd: |
      set -o pipefail
      echo 'show servers state' \
      | nc -U {{ individual_instance_dir }}/run/haproxy.sock \
      > {{ individual_instance_dir }}/run/global-state
    executable: /bin/bash
  become: yes
  changed_when: true
  register: haproxy_sock_result
  retries: 10
  delay: 3
  until: haproxy_sock_result.rc == 0
  when: haproxy_config.changed

- name: Update server states file
  include_tasks: update_states_file.yml
  vars:
    cfg_file: "{{ individual_instance_dir }}/etc/{{ clustered_instance_name }}.cfg"
    states_file: "{{ individual_instance_dir }}/run/global-state"

- name: Reload haproxy
  # This cannot be a handler as `include_role` is not supported in handlers
  vars:
    name: "{{ container_name }}"
    signal: HUP
  include_role:
    name: container_runner
    tasks_from: send_signal.yml
  when:
    - (
        haproxy_config.changed
        or sorry_page.changed
        or copy_certificates.changed
        or copy_sqlbillings.changed
      )  # noqa: no-handler

- name: Reset container running fact
  set_fact:
    container_running: false

- name: Wait for container to come up
  include_tasks: wait_container_up.yml
  when: not container_running
  loop: "{{ range(0, 10) | list }}"

- name: Assert that container is running
  assert:
    that: container_running
    fail_msg: "Container is not running."
