---
- name: Calculate and populate individual instance facts
  include_tasks: calculations.yml

- name: Create directory {{ item }}
  file:
    dest: "{{ individual_instance_dir }}/{{ item.path }}"
    state: directory
    mode: "{{ item.mode }}"
    owner: "{{ subuser.subuid }}"
    group: "{{ subuser.subgid }}"
  become: yes
  loop:
    - path: ''
      mode: a=rx
    - path: etc/certs
      mode: u=rx,go=
    - path: etc/sorry_pages
      mode: a=rx
    - path: run
      mode: u=rwx,go=

- name: Copy sorry pages to destination
  include_tasks: copy_sorry_pages.yml
  vars:
    sorry_pages_list: "{{ backend_item.value.sorry_pages }}"
  when: "'sorry_pages' in backend_item.value"
  loop: "{{ static_backends | dict2items }}"
  loop_control:
    loop_var: backend_item

- name: Create socket and global-state files
  file:
    path: "{{ individual_instance_dir }}/run/{{ item }}"
    state: touch
    mode: u=rw,go=r
    owner: "{{ subuser.subuid }}"
    group: "{{ subuser.subgid }}"
  loop:
    - global-state
    - haproxy.sock
  become: yes


- name: Template out the haproxy config
  template:
    src: haproxy.cfg.j2
    dest: "{{ individual_instance_dir }}/etc/{{ clustered_instance_name }}.cfg"
    mode: u=r,go=
    owner: "{{ subuser.subuid }}"
    group: "{{ subuser.subgid }}"
  become: yes
  # TODO: validate
  register: haproxy_config

- name: Template out the sorry page
  template:
    src: sorry.http.j2
    dest: "{{ individual_instance_dir }}/etc/sorry.http"
    mode: u=r,go=
    owner: "{{ subuser.subuid }}"
    group: "{{ subuser.subgid }}"
  become: yes
  # TODO: validate
  register: sorry_page

- name: Copy certificates for individual instance
  copy:
    src: "certificates/{{ item }}.pem"
    dest: "{{ individual_instance_dir }}/etc/certs/"
    mode: ug=r,o=
    owner: "{{ subuser.subuid }}"
    group: "{{ subuser.subgid }}"
  become: yes
  loop: "{{ certificates | default([]) }}"
  no_log: true
  register: copy_certificates

- name: Template out the apparmor profile
  template:
    src: apparmor_profile.j2
    dest: "{{ individual_instance_dir }}/apparmor_profile"
    mode: u=r,go=
    owner: root
    group: root
    validate: apparmor_parser -Q %s
  become: yes
  register: apparmor_profile_config

- name: Check if apparmor profile is loaded
  command: apparmor_status --json
  become: yes
  changed_when: no
  register: apparmor_status
  when: apparmor_profile_config is not changed

- name: Immediately load apparmor profile
  command: "apparmor_parser -r -W {{ individual_instance_dir }}/apparmor_profile"
  become: yes
  changed_when: yes
  when: >-  # noqa: no-handler
    apparmor_profile_config is changed
    or container_name not in (apparmor_status.stdout | from_json).profiles

- name: Check if container exists
  vars:
    name: "{{ container_name }}"
  include_role:
    name: container_runner
    tasks_from: check_container_exists.yml

- name: Deploy the haproxy container
  include_role:
    name: container_runner
  vars:
    name: "{{ container_name }}"
    workload: deployment
    image: "wtgopstools.azurecr.io/dante/haproxy:{{ container.haproxy_version }}-{{ container.haproxy_os }}"
    startup_command: >-
      -f /etc/haproxy/{{ clustered_instance_name }}.cfg
    restart: never
    volumes:
      - "{{ individual_instance_dir }}/etc:/etc/haproxy:z"
      - "{{ individual_instance_dir }}/run:/var/run/haproxy:z"
    net_host: no
    ports: >-
      [
        {% for host_port, container_port in docker_port_map.items() | sort %}
        '{{ host_port }}:{{ container_port }}',
        {% endfor %}
      ]
    apparmor_profile: "{{ container_name }}"
    container_user: "{{ user.uid }}:{{ user.group }}"
    container_dir: "{{ individual_instance_dir }}"
    resources:  # TODO review, probably make configurable
      production:
        cpu: 1000m
        memory: 1000Mi
      simulation:
        cpu: 200m
        memory: 100Mi

- name: Mark as needs-restart if needed
  template:
    src: needs_restart.j2
    dest: "{{ needs_restart_marker }}"
    mode: a=r
  become: yes
  when: need_restart

- name: Check for needs-restart marker
  stat:
    path: "{{ needs_restart_marker }}"
  register: needs_restart_stat

- name: Assert no restart needed (now or on a previous run)
  assert:
    that: not needs_restart_stat.stat.exists

- name: Save Global state to allow faster reloads
  shell:
    cmd: |
      set -o pipefail
      echo 'show servers state' \
      | nc -U {{ individual_instance_dir }}/run/haproxy.sock \
      > {{ individual_instance_dir }}/run/global-state
    executable: /bin/bash
  become: yes
  changed_when: true
  when:
    - container_exists
    - haproxy_config.changed

- name: Update server states file
  include_tasks: update_states_file.yml
  vars:
    cfg_file: "{{ individual_instance_dir }}/etc/{{ clustered_instance_name }}.cfg"
    states_file: "{{ individual_instance_dir }}/run/global-state"
  when:
    - container_exists
    - haproxy_config.changed

- name: Reload haproxy
  # This cannot be a handler as `include_role` is not supported in handlers
  vars:
    name: "{{ container_name }}"
    signal: HUP
  include_role:
    name: container_runner
    tasks_from: send_signal.yml
  when:
    - container_exists
    - haproxy_config.changed or sorry_page.changed or copy_certificates.changed  # noqa: no-handler
