---
- name: Calculate instance facts
  set_fact:
    instance_dir: "/mnt/data1/containers/iris_{{ inventory_hostname }}"

- name: Create directory {{ item }}
  file:
    dest: "{{ instance_dir }}/{{ item }}"
    state: directory
    mode: a=rx
  become: yes
  loop: [etc, run]

- name: Populate backends variable for instance
  set_fact:
    backends: "{{ hostvars['localhost'].complete_iis_data.instances[original_instance_name] }}"
  when: 
  - "original_instance_name in hostvars['localhost'].complete_iis_data.instances"
  - "complete_iis_data in hostvars['localhost']"

- name: Template out the haproxy config
  template:
    src: haproxy.cfg.j2
    dest: "{{ instance_dir }}/etc/haproxy.cfg"
    mode: u=r,go=
  become: yes
  # TODO: validate
  register: haproxy_config

- name: Template out the sorry page
  template:
    src: sorry.http.j2
    dest: "{{ instance_dir }}/etc/sorry.http"
    mode: u=r,go=
  become: yes
  # TODO: validate
  register: sorry_page

- name: Deploy the haproxy container
  include_role:
    name: container_runner
  vars:
    name: "iris_{{ inventory_hostname }}"
    workload: deployment
    image: wtgopstools.azurecr.io/dante/haproxy:2.1.4  # TODO configurable
    restart: "{{ haproxy_config.changed or sorry_page.changed }}"
    environ:
      - "iris_haproxy_config_checksum={{ haproxy_config.checksum }}"
      - "iris_sorry_page_checksum={{ sorry_page.checksum }}"
    volumes:
      - "{{ instance_dir }}/etc:/usr/local/etc/haproxy:z"
      - "{{ instance_dir }}/run:/var/run/haproxy:z"
    container_dir: "{{ instance_dir }}"
    resources:  # TODO review, probably make configurable
      production:
        cpu: 1000m
        memory: 1000Mi
      simulation:
        cpu: 200m
        memory: 100Mi
