---
- name: Pause for 5 seconds before check
  ansible.builtin.pause:
    seconds: 5

- name: Set container engine
  include_role:
    name: container_runner
    tasks_from: define_engine.yml

- name: Check if container exists
  command: >-
    {{ engine }} ps
  changed_when: false
  become: yes
  register: container_list

- name: Reset container running fact
  set_fact:
    container_running: false

- name: Set container_running variable
  set_fact:
    container_running: true
  when:
    - container_list is not skipped
    - container_name in item
    - "'Up ' in item"
  loop: "{{ container_list.stdout_lines }}"
