---
- name: Set container engine
  include_role:
    name: container_runner
    tasks_from: define_engine.yml

- name: Wait until container is running (first check)
  command: >
    {{ engine }} inspect
    -f '{{"{{"}}.State.Status{{"}}"}}'
    {{ container_name }}
  register: inspect_1
  retries: 20
  delay: 5
  changed_when: false
  failed_when: false
  until:
    - inspect_1.rc == 0
    - inspect_1.stdout == "running"

- name: Pause for 5 seconds before second check
  ansible.builtin.pause:
    seconds: 5

- name: Verify container is still running (second check)
  command: >
    {{ engine }} inspect
    -f '{{"{{"}}.State.Status{{"}}"}}'
    {{ container_name }}
  register: inspect_2
  changed_when: false
  failed_when:
    - inspect_2.rc != 0
    - inspect_2.stdout != "running"
