---
# NOTE: The 'find' task below registers a variable
# 'telegraf_unit_file' which is used by the handler in 'handlers/main.yml'
# to conditionally restart the service. This creates a dependency between
# this task file and the handler file.
- name: Check if telegraf's main service unit file exists
  find:
    paths:
      - /usr/lib/systemd/system
      - /etc/systemd/system
    patterns: 'telegraf.service'
  register: telegraf_unit_file

- name: Ensure telegraf.d directory exists
  become: yes
  file:
    path: /etc/telegraf/telegraf.d/
    state: directory
    owner: root
    group: root
    mode: "u=rwx,g=rx,o=rx"

- name: Copy Prometheus config to telegraf.d
  become: yes
  template:
    src: prometheus.conf.j2
    dest: /etc/telegraf/telegraf.d/prometheus.conf
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  notify: Restart telegraf

- name: Check if conntrack proc files exist as a prerequisite
  # This task checks that both required kernel metric files are present.
  # The task uses a loop to check each file path with the stat module.
  stat:
    path: "{{ item }}"
  loop:
    - /proc/sys/net/netfilter/nf_conntrack_max
    - /proc/sys/net/netfilter/nf_conntrack_count
  register: files_check

- name: Configure Telegraf for conntrack monitoring
  # This block groups all tasks related to the conntrack feature.
  # It will only run if all prerequisite checks pass.
  become: yes
  when:
    - >
      (files_check.results | selectattr('stat.exists', 'equalto', true) | list | length) ==
      (files_check.results | length)
  block:
    - name: Create conntrack log directory
      # Creates the directory where metrics will be written.
      # Ownership is set to 'ansible_user', as telegraf runs as this user.
      # Generally, it should be 'dante'.
      file:
        path: /var/log/conntrack/
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "u=rwx,g=rx,o=rx"

    - name: Copy conntrack telegraf config
      # Copies the new configuration file to the telegraf.d directory.
      copy:
        src: conntrack.conf
        dest: /etc/telegraf/telegraf.d/conntrack.conf
        owner: root
        group: root
        mode: "u=rw,g=r,o=r"
      notify: Restart telegraf
