---
- name: Set openssl config path
  set_fact:
    openssl_config: /etc/ssl/openssl.cnf

- name: Enable providers section
  lineinfile:
    path: "{{ openssl_config }}"
    regexp: '# providers = provider_sect'
    line: 'providers = provider_sect'
  become: yes

- name: Add legacy section reference
  lineinfile:
    path: "{{ openssl_config }}"
    insertafter: 'default = default_sect'
    line: "legacy = legacy_sect"
  become: yes

- name: Activate default section
  lineinfile:
    path: "{{ openssl_config }}"
    insertafter: '[default_sect]'
    regexp: '# activate = 1'
    line: 'activate = 1'
  become: yes

- name: Add and activate legacy section
  blockinfile:
    path: "{{ openssl_config }}"
    content: |
      [legacy_sect]
      activate = 1
  become: yes
