---
- name: Install keepalived, registering if needed
  block:
    - name: Register test Red Hat license (simulation only)
      include_role:
        name: system_license
      when:
        - simulation
        - 'os == "rhel"'

    - name: Install keepalived
      package:
        name: keepalived
        state: present
      become: yes

  always:
    - name: Unregister test Red Hat license (simulation only)
      include_role:
        name: kvm_cleanup
        tasks_from: unregister_rhel.yml
      when:
        - simulation
        - 'os == "rhel"'

- name: Configure keepalived
  vars:
    priority_list: [250, 200, 150, 100, 50]
    vrrp_instances: >-
      [
        {% for machine_cluster_name, machine_cluster_config in machine_clusters.items() %}
        {% for floating_ip in machine_cluster_config.floating_ips %}
          {
            'machine_cluster_name': {{ machine_cluster_name | to_json }},
            'config': {{ floating_ip | to_json }},
            'calculated_priority': {{
              (
                floating_ip.priority
                | zip(priority_list)
                | selectattr('0', 'eq', inventory_hostname)
                | first
              )[1],
            }},
            'virtual_router_id': {{
                floating_ip.virtual_router_id | default(
                  floating_ip.ip | ipaddr('int') % 256
                )
            }},
          },
        {% endfor %}
        {% endfor %}
      ]
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    mode: u=rw,go=r
  become: yes
  notify: Reload keepalived

- name: Start and enable keepalived
  service:
    name: keepalived
    state: started
    enabled: yes
  become: yes
