---
- name: Install keepalived, registering if needed
  block:
    - name: Register test Red Hat license (simulation only)
      include_role:
        name: system_license
      when:
        - simulation
        - 'os == "rhel9"'

    - name: Refresh apt cache (Ubuntu only)
      apt:
        update_cache: yes
        autoclean: yes
      become: yes
      when:
        - simulation
        - 'os == "ubuntu"'

    - name: Install keepalived
      package:
        name: keepalived
        state: present
      become: yes

  always:
    - name: Unregister test Red Hat license (simulation only)
      include_role:
        name: kvm_cleanup
        tasks_from: unregister_rhel.yml
      when:
        - simulation
        - 'os == "rhel9"'

- name: Keepalived systemd override directory
  file:
    dest: /lib/systemd/system/keepalived.service.d
    state: directory
    mode: a=rx
  become: yes

- name: Keepalived warm-up
  vars:
    warm_up: "{{ 3 if simulation else 8 * 60 }}"  # 8 minutes wait before daemon start
    start_up: 90  # default 90s timeout for daemon start-up
  copy:
    content: |
      ### This file is deployed by Iris ###
      [Service]
      ExecStartPre=/bin/sleep {{ warm_up }}
      TimeoutStartSec={{ warm_up | int + start_up }}
    dest: /lib/systemd/system/keepalived.service.d/keepalived-overrides.conf
    mode: u=rw,go=r
  become: yes
  register: keepalived_warmup

- name: Find cluster that contains the current host
  set_fact:
    current_cluster: "{{ item.key }}"
  loop: "{{ machine_clusters | dict2items }}"
  when: inventory_hostname in item.value.machines

- name: Configure keepalived
  vars:
    priority_list: [250, 200, 150, 100, 50]
    peer_ips: >-
      [
        {% for h in machine_clusters[current_cluster].machines.keys() if h != inventory_hostname %}
          "{{ hostvars[h].ansible_host }}"{% if not loop.last %}, {% endif %}
        {% endfor %}
      ]
    vrrp_instances: >-
      {%- set result = [] -%}
      {%- for machine_cluster_name, machine_cluster_config in machine_clusters.items() -%}
        {%- for floating_ip in machine_cluster_config.floating_ips -%}
          {%- set idx = floating_ip.priority.index(inventory_hostname)
                       if inventory_hostname in floating_ip.priority
                       else -1 -%}
          {%- if idx >= 0 -%}
            {%- set calculated = priority_list[idx] -%}
          {%- else -%}
            {%- set calculated = priority_list[-1] -%}
          {%- endif -%}
          {%- set _ = result.append({
                'machine_cluster_name': machine_cluster_name,
                'config': floating_ip,
                'calculated_priority': calculated,
                'virtual_router_id': floating_ip.virtual_router_id
              }) -%}
        {%- endfor -%}
      {%- endfor -%}
      {{ result }}
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    mode: u=rw,go=r
  become: yes
  notify: Reload keepalived

- name: Start and enable keepalived
  systemd:
    name: keepalived
    state: started
    enabled: yes
    daemon_reload: "{{ keepalived_warmup is changed }}"
  become: yes
