---
individual_instance_defaults:
  instance:
    # TODO: this should probably just be the name?
    # log_name: datacentre - env - context - function
    log_name: iris-default-instance-name
    processes: 1
    threads: 8
    maxconn: 200000
    haproxy_version: "2.4.19"

  stats:
    ports:
      file: /var/run/haproxy/haproxy.sock
      socket: 81
      web: 8001

  cipher:
    profiles:
      - best_practice_2023
    bind_options: [no-sslv3, no-tlsv10, no-tlsv11, no-tls-tickets]
    ssl_min: TLSv1.2
    ssl_max: TLSv1.3

  proxy:
    mode: http
    ports:
      http:
        plaintext: [80]
        ssl: [443]
    maxconn: 200000
    fullconn: 5000
    balance: leastconn

  timeouts:
    client: 60
    connect: 60
    server: 300
    tunnel: 3600
    http_keep_alive: 1
    http_request: 60
    queue: 30
    tarpit: 60
