---
individual_instance_defaults:
  defaults:
    mode: http
    log_name: "{{ inventory_hostname }}"
    fullconn: 5000
    balance: leastconn
    health_check_interval: 10s

  global_:
    processes: 1
    threads: 8
    maxconn: 200000

  container:
    haproxy_image_tag: "2.4.19-bullseye"
    port_map:  # convention: backwards starting from 80: 8000
      80: 8000
      81: 7999
      443: 7637
    port_prealloc: []  # pre-allocated ports, eg. [1100-1199, 1500-1699, 8080]
    resources:
      production:
        cpu: 8000m
        memory: 16000Mi
      simulation:
        cpu: 1000m
        memory: 8000Mi

  stats:
    ports:
      file: /var/run/haproxy/haproxy.sock
      socket: 81
      web: 8001

  cipher:
    profiles:
      - best_practice_2023
    bind_options: [no-sslv3, no-tlsv10, no-tlsv11, no-tls-tickets]
    ssl_min: TLSv1.2
    ssl_max: TLSv1.3

  frontend:
    maxconn: 200000
    fullconn: 5000

  timeouts:
    client: 60
    connect: 60
    server: 300
    tunnel: 3600
    http_keep_alive: 1
    http_request: 60
    queue: 30
    tarpit: 60

  features:
    schema_placeholder: false
