---
- name: Create fakeserver directory
  file:
    dest: "{{ working_dir }}/{{ item }}"
    state: directory
    mode: a=rwx
  become: yes
  loop:
    - config
    - public
    - certs

- name: Calculate certificates for the machine
  set_fact:
    certs_list: >
      {{ certs_list | default([]) +
         (hostvars[item].certs_list | default([])) }}
  when:
    - hostvars[item].machine_cluster in machine_clusters
    - '"certs_list" in hostvars[item]'
    - '"tests" in hostvars[item]'
  loop: "{{ groups['clustered_instances'] }}"

- name: Copy certificates for clustered instance
  copy:
    src: "certificates/{{ item }}.pem"
    dest: "{{ working_dir }}/certs/"
    mode: ug=r,o=
    owner: "{{ haproxy_subuser.subuid }}"
    group: "{{ haproxy_subuser.subgid }}"
  become: yes
  loop: "{{ certs_list | default([]) }}"
  no_log: true

- name: Calculate tests for the machine
  set_fact:
    tests_list: "{{ tests_list | default([]) + hostvars[item].tests }}"
  when:
    - hostvars[item].machine_cluster in machine_clusters
    - '"tests" in hostvars[item]'  
  loop: "{{ groups['clustered_instances'] }}"

- name: Deploy fakeserver
  when: tests_list | default([]) | length > 0
  block:
    - name: Calculate all status codes to return
      set_fact:
        status_codes: "{{ (status_codes | default([]) + [item.status]) | unique }}"
      when: not item.ssl
      loop: "{{ tests_list }}"

    - name: Create directories for tests
      file:
        path: "{{ working_dir }}/public{{ item.path | dirname }}"
        state: directory
        recurse: true
        mode: a=rwx
        owner: "{{ haproxy_subuser.subuid }}"
        group: "{{ haproxy_subuser.subgid }}"
      become: yes
      loop: "{{ tests_list }}"

    - name: Create empty files for tests
      file:
        path: "{{ working_dir }}/public{{ item.path }}"
        state: touch
        mode: a=rwx
      loop: "{{ tests_list }}"

    - name: Generate fakeserver config
      template:
        src: nginx.conf.j2
        dest: "{{ working_dir }}/config/nginx.conf"
        mode: a=r
        owner: "{{ haproxy_subuser.subuid }}"
        group: "{{ haproxy_subuser.subgid }}"
      become: yes

    - name: Copy index.html
      copy:
        src: index.html
        dest: "{{ working_dir }}/public/index.html"
        mode: a=r
        owner: "{{ haproxy_subuser.subuid }}"
        group: "{{ haproxy_subuser.subgid }}"
      become: yes

    - name: Generate hosts file for tests
      template:
        src: hosts.j2
        dest: "/etc/hosts"
        mode: ug=rw,o=r
        owner: "{{ haproxy_subuser.subuid }}"
        group: "{{ haproxy_subuser.subgid }}"
      become: yes

    - name: Deploy the fakeserver container
      include_role:
        name: container_runner
      vars:
        name: fakeserver
        workload: deployment
        image: "{{ fakeserver_image }}"
        volumes:
          - "{{ working_dir }}/config:/etc/nginx:z"
          - "{{ working_dir }}/public:/public:z"
          - "{{ working_dir }}/certs:/certs:ro,z"
        ports:
          - 8081:80
          - 8082:443
        net_host: no
        container_dir: "{{ working_dir }}"
        resources:
          simulation:
            cpu: 1000m
            memory: 200Mi

    - name: Set container engine
      include_role:
        name: container_runner
        tasks_from: define_engine.yml

    - name: Wait for fakeserver to come online
      command: "{{ engine }} ps --filter name=fakeserver --filter status=running"
      register: result
      changed_when: false
      retries: 10
      delay: 5
      until: (result.stdout_lines | length) > 1
      become: yes
