---
# There is an issue currently with url module accepting int only for status_code. lynt can't convert str to int
- name: Perform tests  # noqa args[module]
  uri:
    follow_redirects: none
    use_proxy: 'no'
    url: >-
      http{{ 's' if item.ssl else '' }}://{{ item.host }}:{{
        simulation_ports.ssl[0] if item.ssl else simulation_ports.plaintext[0]
      }}{{ item.path }}
    method: GET
    headers:
      Host: "{{ item.host }}"
    validate_certs: 'yes'
    status_code: "{{ item.status }}"
  retries: "{{ 50 if index == 0 else 20 }}"
  delay: 1
  loop: "{{ tests }}"
  loop_control:
    index_var: index
  environment:
    no_proxy: "{{ inventory_hostname }},{{ item.host }},{{ item.host }}"
  register: test_result
  until:
    - "'status' in test_result"
    - test_result.status == item.status
