---
# Verify that the set of VIPs active in the running cluster matches exactly those defined
# in the IRIS configuration, and that each VIP appears only once.
- name: Load machine clusters
  vars:
    content: >-
      {{ lookup('file', fname) | from_yaml }}
  set_fact:
    cluster_data: >-
      {{ cluster_data | default({}) | combine(content) }}
  loop: "{{ lookup('fileglob', '../../../../data/machine_clusters/*.y*ml', wantlist=True) }}"
  loop_control:
    loop_var: fname

- name: Get VRRP IP addresses on each machine
  shell:
    cmd: |
      set -o pipefail
      ip -4 a | grep vrrp | grep -oE 'inet ([0-9]{1,3}\.){3}[0-9]{1,3}' | awk '{print $2}'
    executable: /bin/bash
  changed_when: false
  delegate_to: "{{ host_in_cluster }}"
  failed_when: false
  register: vrrp_ips
  loop: "{{ cluster_machines }}"
  loop_control:
    loop_var: host_in_cluster
  vars:
    cluster_machines: "{{ cluster_data[cluster_name]['machines'] | dict2items | map(attribute='key') | list }}"

- name: Set machine vips
  set_fact:
    machine_vips: >-
      {{
        machine_vips | default({}) |
        combine({vrrp_result['host_in_cluster']: vrrp_result.get('stdout_lines', [])})
      }}
  loop: "{{ vrrp_ips.results | default([]) }}"
  loop_control:
    loop_var: vrrp_result

- name: Debug machine vips
  debug:
    msg: >-
      VIP in cluster {{ cluster_name }}
      {{ machine_vips }}

- name: Assert that all floating IPs are present in the VIP list
  assert:
    that:
      - all_vip_list | length == cluster_floating_ips | length
      - all_vip_list | sort == cluster_floating_ips | sort
    fail_msg: "VIP lists do not match! Please check."
  vars:
    all_vip_list: "{{ machine_vips.values() | flatten | list }}"
    cluster_floating_ips: "{{ cluster_data[cluster_name]['floating_ips'] | map(attribute='ip') | list }}"
