---
- name: Compare group files
  block:
    - name: Compare the first file to others
      shell: diff -q "{{ group_item.value[0] }}" "{{ item }}"
      register: diff_result
      failed_when: false
      changed_when: false
      loop: "{{ group_item.value[1:] }}"

    - name: Show different stats
      fail:
        msg: >-
          The instance {{ group_item.key }} got the different stats: {{ item }}
      when: item.rc != 0
      loop: "{{ diff_result.results }}"
  delegate_to: localhost
  run_once: true
  when: group_item.value | length > 1
