---
- name: Load data file
  set_fact:
    data: "{{ lookup('file', data_file) | from_yaml }}"

- name: Read unique haproxy users
  set_fact:
    unique_users: "{{ data.values() | map(attribute='user') | list | unique }}"

- name: Read passwords from key vault
  include_tasks: read_password.yml
  loop: "{{ unique_users }}"
  loop_control:
    loop_var: user_name

- name: Read passwords from key vault
  include_tasks: process_backend.yml
  loop: "{{ data }}"
  loop_control:
    loop_var: backend
