---
- name: "Get password for user {{ user_name }}"
  include_role:
    name: azure_keyvault
    tasks_from: get_secret.yml
  vars:
    azure_kv_secret_name: "{{ user_name  }}"

- name: Update credentials
  set_fact:
    credentials: "{{ credentials | default({}) | combine({user_name: return_secret_value}) }}"
