---
- name: Create certificates directory
  file:
    dest: "certificates/{{ inventory_hostname }}"
    state: directory
    mode: u=rwx,go=
  delegate_to: localhost

- name: Get certificate
  include_role:
    name: azure_keyvault
    tasks_from: get_secret.yml
    apply:
      delegate_to: localhost
  vars:
    azure_kv_secret_name: "{{ certificate_name }}"
    curl:
      retries: 2
      delay: 5

- name: Check that certificate exists in key vault
  assert:
    that: return_secret_value
    fail_msg: "{{ certificate_name }} does not exist in key vault"

- name: Save certificate to file
  copy:
    dest: "certificates/{{ inventory_hostname }}/{{ certificate_name }}.pem"
    content: "{{ return_secret_value }}"
    mode: u=rw,go=
  delegate_to: localhost
  no_log: true

- name: Call certificate validation command
  command: "openssl rsa -noout -check -in certificates/{{ inventory_hostname }}/{{ certificate_name }}.pem"
  changed_when: False
  register: cert_check_result

- name: Check that certificate is valid
  assert:
    that:
      - cert_check_result.stdout is defined
      - "'RSA key ok' in cert_check_result.stdout"
    fail_msg: "{{ cert_check_result.stderr }}"
