---
- name: Register test Red Hat subscription
  shell: |
    set -euxo pipefail

    subscription-manager unregister || true
    subscription-manager register --org={{ test_organisation }} --activationkey={{ test_activation_key }}
  changed_when: true
  become: yes
  when:
    - simulation
    - 'os == "rhel"'
  notify: Unregister Red Hat subscription
