---
- name: Setup rsyslog
  include_role:
    name: rsyslog  # from the Dante SOE
  vars:
    rsyslog_udp_listen_addr: "172.17.0.1"

- name: Rsyslog rules for haproxy logs
  copy:
    src: 30-iris.conf
    dest: /etc/rsyslog.d/30-iris.conf
    mode: u=rw,go=r
  become: yes
  notify: restart rsyslog  # noqa: name[casing] - from the Dante SOE
