---
- name: Iris Cluster Maintenance
  hosts: server_loadbalancer_iris:&maintainable:!no_dante
  gather_facts: no
  serial: 1
  tasks:
    - name: Calculate BMC IP
      set_fact:
        bmc_ip: "{{ virgil_consoles | map(attribute='ip') | first }}"

    - name: Calculate ztp_server and iso_url_base
      set_fact:
        ztp_server: "{{ hostvars[item]['virgil_ip_primary'] }}"
        iso_url_base: "http://{{ hostvars[item]['virgil_ip_oob_dante'] }}:8089/server-images"
      when:
        - virgil_hostname != hostvars[item]['virgil_hostname']
        - hostvars[item]['virgil_dante']
      loop: "{{ groups['mgmt'] }}"

    - name: Get server ISOs from Pure to ZTP Server
      include_role:
        name: rebuild_xclarity_server
        tasks_from: iso_pure_to_mgmt.yml

    - name: Generate secrets for password rotation
      include_role:
        name: azure_keyvault
        tasks_from: generate_linux_secrets.yml

    - name: Prepare to rebuild the server
      when: skip_pre_checks != 'true'
      block:
        - name: Stop and disable keepalived service
          systemd:
            name: keepalived
            state: stopped
            enabled: no
          become: yes

        - name: Unroll Elastic Agent
          include_role:
            name: wtg.monitoring_agents.elastic_agent
            tasks_from: unroll_agents.yml

        - name: Wait for a few seconds to allow VIPs on this machine to be released
          pause:
            seconds: 5

        - name: Check VIPs
          include_role:
            name: cluster_health_checks
            tasks_from: check_vips.yml

        - name: Assert that all VIPs are only present on other machines
          assert:
            that:
              - machine_vips[specific_host] | length == 0
            fail_msg: "Found VIPs still on {{ specific_host }}: {{ machine_vips[specific_host] }}"

    - name: Rebuild node
      include_role:
        name: node_maintenance
        tasks_from: rebuild_node.yml

    - name: Await rebuild step to finish
      include_role:
        name: node_maintenance
        tasks_from: wait_rebuild_node.yml

    - name: Install Telegraf
      include_role:
        name: telegraf_config
        tasks_from: basic_install.yml

    - name: Wait for Iris run - timeout 60mins, poll every 10s
      wait_for:
        path: "{{ iris_run_directory }}/{{ iris_run_file }}"
        sleep: 10
        timeout: 3600
      register: iris_run_time
      vars:
        iris_run_directory: "/var/log/iris"
        iris_run_file: "iris_run.log"

    - name: Report Iris run time
      debug:
        msg: "Waited {{ iris_run_time.elapsed }} seconds for iris run file to appear"

    - name: Check keepalived
      include_role:
        name: cluster_health_checks
        tasks_from: check_keepalived.yml

    - name: Check VIPs
      include_role:
        name: cluster_health_checks
        tasks_from: check_vips.yml
