---
- name: Trigger next IRIS maintenance
  hosts: localhost
  gather_facts: no
  vars:
    trigger_iris_chains:
      AU2:
        - au2-prod-internal-1
        - au2-prod-frontend-1
      DE1:
        - de1-prod-internal-1
        - de1-prod-frontend-1
      US2:
        - us2-corp-internal-1
        - us2-prod-frontend-1
  tasks:
    - name: Get next cluster in the chain
      set_fact:
        next_cluster: "{{ trigger_iris_chains[dc][trigger_iris_chains[dc].index(cluster_name) + 1] }}"
      when:
        - cluster_name in trigger_iris_chains[dc]
        - trigger_iris_chains[dc].index(cluster_name) + 1 < (trigger_iris_chains[dc] | length)

    - name: Display next cluster
      debug:
        msg: "Next cluster after {{ cluster_name }} in {{ dc }}: {{ next_cluster }}"
      when: next_cluster | default('') | length > 0

    - name: Trigger next IRIS maintenance pipeline
      include_role:
        name: trigger_iris_pipeline
        tasks_from: trigger_maintenance.yml
      when: next_cluster | default('') | length > 0
