---
- name: Get the Key Vault Name
  uri:
    url: "https://{{ cms_endpoint }}/cms/v1/certificate/{{ cert.domain }}/{{ cert.name }}"
    method: GET
    headers:
      Content-Type: application/json
    status_code:
      - 200
      - 201
      - 404
    use_proxy: "{{ use_proxy | default(true) }}"
  register: cms_service_output
  retries: 24
  delay: 5
  until: not cms_service_output.failed
  when: 'cert.key_vault_name is not defined'

- name: Assign key_vault_name for certs_data (from cache)
  set_fact:
    updated_cert: "{{ cert }}"
  when:
    - 'cert.key_vault_name is defined'

- name: Assign key_vault_name for certs_data (from cms)
  set_fact:
    updated_cert: "{{ cert | combine({'key_vault_name': cms_service_output.json.keyvault}) }}"
  when:
    - 'cert.key_vault_name is not defined'
    - 'cms_service_output.json.keyvault is defined'

- name: Assign default key_vault_name for cert
  set_fact:
    updated_cert: "{{ cert | combine({'key_vault_name': 'kv-wtg-iris-prod'}) }}"
  when:
    - 'cert.key_vault_name is not defined'
    - 'cms_service_output.json.keyvault is not defined'

- name: Append updated cert to updated_certs list
  set_fact:
    updated_certs: "{{ (updated_certs | default([])) + [updated_cert] }}"
