---
- name: Create certificates directory
  file:
    dest: "{{ certs_folder }}/"
    state: directory
    mode: u=rwx,go=

- name: Get certificate
  include_role:
    name: azure_keyvault
    tasks_from: get_secret_cms.yml
  vars:
    azure_cms_kv_name: "{{ key_vault_name }}"
    curl:
      retries: 2
      delay: 5

- name: ??
  debug:
    var: certificate_domain

- name:
  debug:
    var: real_certificate_name

- name: Get intermediate certificate if required
  uri:
    url: "https://{{ cms_endpoint }}/cms/v1/certificate/{{ certificate_domain }}/{{ real_certificate_name }}"
    method: GET
    headers:
      Content-Type: application/json
    status_code:
      - 200
      - 201
      - 404
    use_proxy: "{{ use_proxy | default(true) }}"
  register: cms_service_output
  retries: 24
  delay: 5
  until: not cms_service_output.failed
  when:
    - intermediate
    - "key_vault_name != 'kv-wtg-iris-prod'"

- name: Append intermediate certificate
  set_fact:
    return_secret_value: >-
      {{ return_secret_value |
         append_intermediate_certificate(cms_service_output.json.certificate) }}
  when:
    - intermediate
    - "key_vault_name != 'kv-wtg-iris-prod'"

- name: Save certificate to file
  copy:
    dest: "{{ certs_folder }}/{{ real_certificate_name }}.pem"
    content: "{{ return_secret_value }}"
    mode: u=rw,go=
  no_log: true
