---
- name: Create certificates directory
  file:
    dest: "{{ certs_folder }}/"
    state: directory
    mode: u=rwx,go=

- name: Get certificate
  include_role:
    name: azure_keyvault
    tasks_from: get_secret_cms.yml
  vars:
    azure_cms_kv_name: "{{ key_vault_name }}"
    curl:
      retries: 2
      delay: 5

- name: Save certificate to file
  copy:
    dest: "{{ certs_folder }}/{{ real_certificate_name }}.pem"
    content: "{{ return_secret_value }}"
    mode: u=rw,go=
  no_log: true
