---
- name: Load certificates to be downloaded from audit files
  set_fact:
    updated_certs: "{{ playbook_dir | read_audit_certs(target_dc | default('')) }}"

- name: Download the certificate - Iris KV
  include_tasks: download_and_save_iris_certificate.yml
  vars:
    key_vault_name: 'kv-wtg-iris-prod'
    certificate_name: "{{ item.name }}"
  loop: "{{ (check_all_certs | default(true)) | ternary(updated_certs, updated_certs[:1]) }}"
  when: "item.key_vault_name == 'kv-wtg-iris-prod'"

- name: Download the certificate - CMS
  include_tasks: download_and_save_cms_certificate.yml
  vars:
    key_vault_name: "{{ item.key_vault_name }}"
    real_certificate_name: "{{ item.name }}"
    certificate_name: 'certificate'
  loop: >
    {{
      (check_all_certs | default(true))
      | ternary(updated_certs, updated_certs | selectattr('name', 'equalto', 'star-wisetechglobal-com') | list)
    }}
  when: "item.key_vault_name != 'kv-wtg-iris-prod'"

- name: Validate certificates
  include_tasks: validate_certificate.yml
