---
- name: Template out the iptables restore file
  template:
    src: iptables.j2
    dest: "/etc/iptables"
    mode: a=r
  become: yes

- name: Immediately apply the iptables restore file
  command: iptables-restore /etc/iptables
  become: yes
  changed_when: true  # TODO can we determine whether any changes were made?
