---
- name: Deploy sysctl values
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    sysctl_set: true
  loop: >-
    {{
      worker_defaults.sysctl_values.common
      | combine(worker_defaults.sysctl_values[virgil_os_variant])
      | dict2items
    }}
  become: yes
