---
- name: Set Virgil-like facts for the machines
  hosts: target_machines
  gather_facts: no
  tasks:
    - name: Set Virgil-like facts for the machines
      set_fact:
        virgil_os_family: linux
        virgil_os_variant: "{{ os_variant }}"
        virgil_mac_oob_dante: '...'
        virgil_hostname: "{{ inventory_hostname }}"
        virgil_groups: ['mgmt']  # TODO: confirm
        virgil_port_oob_dante: eno1
        virgil_internal_fqdn: "{{ inventory_hostname }}"

- name: Import IIS data
  import_playbook: import_iis_data.yml
  when:
    - enable_dynamic_backends | default(true)
    - not use_local_backends | default(false)

- name: Load machine clusters configuration
  import_playbook: load_machine_clusters.yaml

- name: Load static backend configuration
  import_playbook: load_static_backends.yaml

- name: Load ACLs
  import_playbook: load_acls.yaml

- name: Load actions
  import_playbook: load_actions.yaml

- name: Load ciphers
  import_playbook: load_ciphers.yaml

- name: Generate the individual instance inventory entries
  import_playbook: generate_individual_instances.yaml
