---
- name: Check and save certificates
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Calculate certificates to download
      set_fact:
        certs_list: "{{ (certs_list | default([]) + hostvars[item].certificates) | unique }}"
      when: '"certificates" in hostvars[item]'
      loop: "{{ groups['clustered_instances'] }}"

    - name: Get certificate
      include_role:
        name: check_certificates
        tasks_from: download_and_save.yml
      loop: "{{ certs_list | default([]) }}"
      loop_control:
        loop_var: certificate_name

    - name: Validate certificate
      include_role:
        name: check_certificates
        tasks_from: validate_certificate.yml
      loop: "{{ certs_list | default([]) }}"
      loop_control:
        loop_var: certificate_name
