---
- name: Checks on the machines
  hosts: target_machines
  strategy: free
  # can use "serial: 1" or "throttle: 1" to process machines one by one, where needed
  gather_facts: no
  force_handlers: yes
  tasks:
    - name: Placeholder
      debug:
        msg: per-machine checks

- name: Checks on the individual instances
  hosts: individual_instances
  strategy: free
  gather_facts: no
  force_handlers: yes
  tasks:
    - name: Check the individual_instances
      include_role:
        name: iris_haproxy
        tasks_from: check_individual_instances.yml

- name: Per-clustered-instance checks
  hosts: clustered_instances
  strategy: free
  gather_facts: no
  force_handlers: yes
  tasks:
    - name: Placeholder
      debug:
        msg: per-clustered_instance checks
