---
- name: Calculate instance inventory entrance
  import_playbook: calculate_instances.yml

- name: Check and save certificates
  hosts: localhost
  gather_facts: yes
  tasks:
    - name: Get certificates
      include_role:
        name: azure_keyvault
        tasks_from: get_secret.yml        
      vars:
        azure_kv_secret_name: ahwprd-webtracker-carozplus-com
        curl.retries: 2
