---
- name: Collect sites_data
  hosts: au2sandinternal1 # clustered_instances
  gather_facts: no
  tasks:
    - name: Collect IIS data
      include_role:
        name: collect_sites
      vars:
        upload_iis_data: false

    # - name: Read file content
    #   command: "ls iis_sites/{{ inventory_hostname }}"
    #   delegate_to: localhost
    #   register: file_output

    - name: Include vars of IIS sites to clustered_instance_name variable
      set_fact:
        complete_iis_data: "{{ lookup('template', 'roles/iris_haproxy/templates/process_iis_data.j2') | from_yaml }}"

    - debug:
        var: complete_iis_data