---
- name: Import IIS data
  import_playbook: import_iis_data.yml
  when: not simulation

- name: Load static backend configuration
  import_playbook: load_backends.yaml
  when: not simulation

- name: Generate the "instance" inventory entries
  hosts: localhost
  strategy: linear
  gather_facts: no
  force_handlers: yes
  tasks:
    - name: Create instance inventory entry
      vars:
        machine: "{{ hostvars[item.machine_name] }}"
        cluster: "{{ hostvars[item.cluster_name] }}"
      add_host:
        name: "{{ item.instance_name }}"
        groups:
          - instances
          - "instances_{{ ['odd', 'even'][i % 2] }}"  # to do half at a time; could also do thirds
        cluster_machine_overrides: "{{ item.cluster_machine_overrides or {} }}"
        machine_name: "{{ item.machine_name }}"
        cluster_name: "{{ item.cluster_name }}"
        # TODO: groups from cluster and machine settings
        ansible_host: "{{ machine.ansible_host }}"

        static_backends: "{{ cluster.static_backends | default({}) }}"

        virgil_orchestrator: container runner  # TODO properly - "{{ machine.virgil_orchestrator }}"
        virgil_os_codename: jammy  # TODO properly - "{{ machine.virgil_os_codename }}"
        virgil_os_variant: "{{ machine.os }}"

      loop: >-
        [
          {% for cluster_name in groups['clusters'] %}
            {% for machine_name, machine_overrides in hostvars[cluster_name].cluster_machines.items() %}
              {
                'machine_name': '{{ machine_name }}',
                'cluster_name': '{{ cluster_name }}',
                'cluster_machine_overrides': {{ machine_overrides | to_json }},
                'instance_name': 'inst_{{ cluster_name }}_{{ machine_name }}',
              },
            {% endfor %}
          {% endfor %}
        ]
      loop_control:
        index_var: i
        label: "{{ item.instance_name }}"

- name: Setup on the machines
  hosts: machines
  strategy: free
  # can use "serial: 1" or "throttle: 1" to process machines one by one, where needed
  gather_facts: no
  force_handlers: yes
  tasks:
    - name: Setup docker
      include_role:
        name: container_runner
        tasks_from: setup.yml
      # TODO: remove when actual prod machines are available
      when: simulation

- name: Setup the instances
  hosts: instances
  strategy: free
  gather_facts: no
  force_handlers: yes
  tasks:
    - name: Calculate instance settings
      vars:
        the_instance: "{{ hostvars[inventory_hostname] }}"
        machine: "{{ hostvars[machine_name] }}"
        cluster: "{{ hostvars[cluster_name] }}"
      set_fact:
        "{{ item }}": >-
          {{
            the_instance[item]
            | combine(cluster[item] | default({}), recursive=true)
            | combine(machine[item] | default({}), recursive=true)
            | combine(cluster_machine_overrides[item] | default({}), recursive=true)
          }}
      loop: [instance, cipher, proxy, timeouts]

    - name: Collect min facts
      ansible.builtin.setup:
        gather_subset: min
      # TODO: remove when actual prod machines are available
      when: simulation

    - name: Deploy the instances
      include_role:
        name: iris_haproxy
        tasks_from: instances.yml
      # TODO: remove when actual prod machines are available
      when: simulation

- name: Setup localhost for s3
  hosts: localhost
  tasks:
    - name: Enable legacy hashes for openssl
      include_role:
        name: collect_sites
        tasks_from: enable_legacy_hashes_for_ssl.yml

    - name: Setup ceph connection
      include_role:
        name: ceph_connection_setup

- name: Per-cluster setup (if needed)
  hosts: clusters
  strategy: free
  gather_facts: no
  force_handlers: yes
  tasks:
    - name: Collect and publish IIS data to ceph
      include_role:
        name: collect_sites
      when: not simulation
