---
- name: Target machines
  import_playbook: target_machines.yaml

- name: Augment the inventory
  import_playbook: augment_inventory.yaml

- name: Create target directory
  hosts: localhost
  strategy: free
  gather_facts: no
  force_handlers: yes
  tasks:
    - name: Create target directory
      file:
        dest: "../generated_configs"
        state: directory
        mode: u=rwx,go=rx

- name: Set dummy values for machines
  hosts: target_machines
  gather_facts: no
  force_handlers: yes
  tasks:
    - name: Set dummy values
      set_fact:
        haproxy_user: ~
        haproxy_subuser: ~

- name: Dump the configs
  hosts: individual_instances
  strategy: free
  gather_facts: no
  force_handlers: yes
  tasks:
    - name: Deploy the individual instances
      include_role:
        name: iris_haproxy
        tasks_from: dump_config.yml
