---
- name: Generate the individual instance inventory entries
  hosts: localhost
  strategy: linear  # required by add_host which bypasses the host loop
  gather_facts: no
  force_handlers: yes
  tasks:
    - name: Print test
      debug:
        msg: test