---
- name: Generate the individual instance inventory entries
  hosts: localhost
  strategy: linear  # required by add_host which bypasses the host loop
  gather_facts: no
  force_handlers: yes
  tasks:
    - name: Build proper list of machines
      set_fact:
        machines_list: >-
          {%- set list = [] -%}
          {%- for clustered_instance_name in groups['clustered_instances'] -%}
            {%- set machines = all_machine_clusters[hostvars[clustered_instance_name].machine_cluster].machines -%}
            {%- for machine_name, machine_cluster_machine_overrides in machines.items() -%}
              {%- set _ = list.append({
                "machine_name": machine_name,
                "clustered_instance_name": clustered_instance_name,
                "individual_instance_name": clustered_instance_name ~ "_" ~ machine_name,
                "machine_cluster_machine_overrides": machine_cluster_machine_overrides
              }) -%}
            {%- endfor -%}
          {%- endfor -%}
          {{ list }}

    - name: Create individual instance inventory entry
      vars:
        machine: "{{ hostvars[item.machine_name] }}"
        clustered_instance: "{{ hostvars[item.clustered_instance_name] }}"
        os_codename:
          ubuntu2204: jammy
          ubuntu2404: noble
          rhel9: plow
      add_host:
        name: "{{ item.individual_instance_name }}"
        groups:
          - individual_instances
          - "individual_instances_{{ ['odd', 'even'][i % 2] }}"  # to do half at a time; could also do thirds
        machine_cluster_machine_overrides: "{{ item.machine_cluster_machine_overrides or {} }}"
        clustered_instance_machine_overrides: >-
          {{ clustered_instance.machine_overrides[item.machine_name] | default({}) }}
        machine_name: "{{ item.machine_name }}"
        clustered_instance_name: "{{ item.clustered_instance_name }}"
        # TODO: groups from clustered instance and machine settings
        ansible_host: "{{ machine.ansible_host }}"
        dc: "{{ clustered_instance.dc }}"
        simulation_ports:
          plaintext: "{{ [4500 + i * 2] }}"
          ssl: "{{ [4500 + i * 2 + 1] }}"

        static_backends: "{{ clustered_instance.static_backends | default({}) }}"
        acls: "{{ clustered_instance.acls }}"
        actions: "{{ clustered_instance.actions }}"
        certificates: "{{ clustered_instance.certificates | map(attribute='name') | list }}"
        tests: "{{ clustered_instance.tests | default([]) }}"
        cipher_profiles: "{{ clustered_instance.cipher_profiles }}"
        custom_defaults: "{{ clustered_instance.custom_defaults | default({}) }}"
        sqlbilling_acl: "{{ clustered_instance.sqlbilling_acl | default([]) }}"
        weborc_url: "{{ clustered_instance.weborc_url | default('') }}"
        iis_servers: "{{ clustered_instance.iis_servers | default([]) }}"
        iis_servers_local: "{{ clustered_instance.iis_servers_local | default([]) }}"
        resources: "{{ clustered_instance.resources | default({}) }}"
        machine_cluster: "{{ clustered_instance.machine_cluster | default('') }}"

        virgil_orchestrator: container runner  # TODO properly - "{{ machine.virgil_orchestrator }}"
        virgil_os_codename: "{{ os_codename[machine.os] }}"
        virgil_os_variant: "{{ machine.os_variant }}"

        ok: ~  # set to `yes` once deployment of instance succeeds

      loop: "{{ machines_list | from_yaml }}"
      loop_control:
        index_var: i
        label: "{{ item.individual_instance_name }}"
      when: item.machine_name in groups['target_machines']

- name: Apply overrides for the individual instances
  hosts: individual_instances
  strategy: free
  gather_facts: no
  force_handlers: yes
  tasks:
    - name: Apply overrides for the individual instances
      # noqa var-naming[no-jinja]  # we do, in fact, intend Jinja for the fact name
      set_fact:
        "{{ item }}": >-
          {{
            individual_instance_defaults[item] | default({})
            | combine(hostvars[clustered_instance_name][item] | default({}), recursive=true)
            | combine(hostvars[machine_name][item] | default({}), recursive=true)
            | combine(machine_cluster_machine_overrides[item] | default({}), recursive=true)
            | combine(clustered_instance_machine_overrides[item] | default({}), recursive=true)
            | combine(hostvars[inventory_hostname][item] | default({}), recursive=true)
          }}
      loop:
        - container
        - global_
        - stats
        - defaults
        - custom_defaults
        - frontend
        - cipher
        - timeouts

    - name: Combine ciphers from all profiles
      set_fact:
        ciphers_upto_tls_v1_2: >-
          {{ (ciphers_upto_tls_v1_2 | default([]) + cipher_profiles[item].ciphers_upto_TLSv1_2) | unique }}
        ciphers_tls_v1_3: >-
          {{ (ciphers_tls_v1_3 | default([]) + cipher_profiles[item].ciphers_TLSv1_3) | unique }}
      loop: "{{ cipher.profiles }}"

    - name: Override ports in simulation
      vars:
        simulation_frontend:
          ports: "{{ simulation_ports }}"
      set_fact:
        frontend: "{{ frontend | combine(simulation_frontend, recursive=true) }}"
      when: simulation

    - name: Calculate port mapping
      vars:
        all_host_ports: >-
            {%- set result = [] -%}
            {%- set _ = result.append(stats.ports.web) -%}
            {%- for port in frontend.ports.plaintext | default([]) -%}
              {%- set _ = result.append(port) -%}
            {%- endfor -%}
            {%- for port in frontend.proxy_ports.plaintext | default([]) -%}
              {%- set _ = result.append(port) -%}
            {%- endfor -%}
            {%- if certificates | default([]) -%}
              {%- for port in frontend.ports.ssl | default([]) -%}
                {%- set _ = result.append(port) -%}
              {%- endfor -%}
              {%- for port in frontend.proxy_ports.ssl | default([]) -%}
                {%- set _ = result.append(port) -%}
              {%- endfor -%}
            {%- endif -%}
            {{ result }}
        port_prealloc_pairs: >-
          {%- set result = [] -%}
          {%- for item in container.port_prealloc -%}
            {%- if item is string and '-' in item -%}
              {%- set _ = result.append(item.split('-') | map('int') | list) -%}
            {%- else -%}
              {%- set _ = result.append([item|int, item|int]) -%}
            {%- endif -%}
          {%- endfor -%}
          {{ result }}
        ports_in_prealloc: >-
          {%- set result = [] -%}
          {%- for port in all_host_ports -%}
            {%- for start, end in port_prealloc_pairs if start <= port <= end -%}
              {%- set _ = result.append(port) -%}
            {%- endfor -%}
          {%- endfor -%}
          {{ result }}
        ports_to_map_individually: >-
          {{ all_host_ports | difference(ports_in_prealloc) }}
      set_fact:
        all_port_map: >-
          {%- set result = {} -%}
          {%- for host_port in all_host_ports -%}
            {%- set _ = result.update({host_port: container.port_map.get(host_port, host_port)}) -%}
          {%- endfor -%}
          {{ result }}
        docker_port_map: >-
          {%- set result = {} -%}
          {%- for host_port in ports_to_map_individually -%}
            {%- set _ = result.update({host_port: container.port_map.get(host_port, host_port)}) -%}
          {%- endfor -%}
          {%- for prealloc in container.port_prealloc -%}
            {%- set _ = result.update({prealloc: prealloc}) -%}
          {%- endfor -%}
          {{ result | from_json }}
        bad_ports: >-
          {{ ports_in_prealloc | intersect(container.port_map) }}

    - name: Print docker map
      debug:
        var: docker_port_map

    - name: Ensure docker_port_map is not empty
      assert:
        that: docker_port_map | length > 0
        quiet: yes
        fail_msg: >-
          No ports are mapped for container

    - name: Check for port map and port preallocation conflict
      assert:
        that: bad_ports | length == 0
        quiet: yes
        fail_msg: >-
          Port(s) {{ bad_ports | join(', ') }} both mapped and preallocated

- name: Set facts on each machine
  hosts: target_machines
  strategy: free
  gather_facts: no
  force_handlers: yes
  tasks:
    - name: Calculate individual instances on each machine
      set_fact:
        individual_instances: >-
          {%- set result = [] -%}
          {%- for individual_instance in groups.individual_instances | default([]) -%}
            {%- if hostvars[individual_instance].machine_name == inventory_hostname -%}
              {%- set _ = result.append(individual_instance) -%}
            {%- endif -%}
          {%- endfor -%}
          {{ result }}

    - name: Calculate stats web ports on each machine
      set_fact:
        stats_web_ports: "{{ stats_web_ports | default([]) + [hostvars[item].stats.ports.web] }}"
      loop: "{{ groups.individual_instances | default([]) }}"
      when: hostvars[item].machine_name == inventory_hostname
