---
- name: Download and initialize instances IIS data
  hosts: localhost
  tasks:
    - name: Setup ceph connection
      include_role:
        name: ceph_connection_setup
      vars:
        proxy_host: "{% if simulation %}192.168.255.254{% endif %}"
        proxy_port: "{% if simulation %}3128{% endif %}"

    - name: Create temporary directory
      tempfile:
        state: directory
      register: temp_path

    - name: Download IIS data from ceph
      command: s3cmd get --recursive  --no-preserve {{ s3_iris_bucket }} {{ temp_path.path }}
      changed_when: true

    - name: Find all instances
      ansible.builtin.find:
        paths: "{{ temp_path.path }}"
        recurse: no
        file_type: directory
      register: instance_folders

    - name: Calculate instances name
      set_fact:
        instance_names: "{{ instance_names | default([]) + [(item.path | split('/'))[-1]] }}"
      loop: "{{ instance_folders.files }}"

    - name: Include vars of IIS sites to instance_name variable
      set_fact: 
        complete_iis_data: "{{ lookup('template','roles/iris_haproxy/templates/process_iis_data.j2') | from_yaml }}"
