---
- name: Download and initialize clustered instance IIS data
  hosts: localhost
  tasks:
    - name: Setup ceph connection
      include_role:
        name: ceph_connection_setup
      vars:
        proxy_host: "{{ ceph_proxy_host | default('') }}"
        proxy_port: "{{ ceph_proxy_port | default('') }}"

    - name: Create temporary directory
      tempfile:
        state: directory
      register: temp_path

    - name: Download IIS data from ceph
      command: >-
        aws --endpoint-url=https://{{ s3_host }}
        s3 cp --recursive
        {{ s3_iris_bucket }} {{ temp_path.path }}
      changed_when: true

    - name: Recursively find all IIS data files
      ansible.builtin.find:
        paths: "{{ temp_path.path }}"
        recurse: yes
      register: iis_files

    - name: Find all clustered_instances
      ansible.builtin.find:
        paths: "{{ temp_path.path }}"
        recurse: no
        file_type: directory
      register: clustered_instance_folders

    - name: Calculate clustered_instances_names
      set_fact:
        clustered_instance_names: >-
          [
            {% for item in clustered_instance_folders.files %}
            {{ (item.path | split('/'))[-1] | to_json }},
            {% endfor %}
          ]

    - name: Report IIS counts
      vars:
        stats:
          data_files_count: "{{ iis_files.files | length }}"
          clustered_instance_count: "{{ clustered_instance_names | length }}"
      debug:
        var: stats

    - name: Map files to paths
      set_fact:
        iis_files: "{{ iis_files.files | map(attribute='path') | unique }}"

    - name: Include vars of IIS sites to clustered_instance_name variable
      set_fact:
        complete_iis_data: "{{ lookup('template', 'roles/iris_haproxy/templates/process_iis_data.j2') | from_yaml }}"

    - name: Show warnings
      debug:
        var: complete_iis_data.warnings
