---
- name: Target machines
  import_playbook: target_machines.yaml

- name: Augment the inventory
  import_playbook: augment_inventory.yaml
  vars:
    enable_dynamic_backends: false

- name: IRIS validation on the target machine
  hosts: target_machines
  tasks:
    - name: Find cluster that contains the current host
      set_fact:
        cluster_name: "{{ item.key }}"
      loop: "{{ machine_clusters | dict2items }}"
      when: inventory_hostname in item.value.machines

    - name: Check keepalived
      include_role:
        name: cluster_health_checks
        tasks_from: check_keepalived.yml

    - name: Check VIPs
      include_role:
        name: cluster_health_checks
        tasks_from: check_vips.yml

- name: IRIS validation on the instances
  hosts: individual_instances
  tasks:
    - name: Set container engine
      include_role:
        name: container_runner
        tasks_from: define_engine.yml

    - name: Check if container is running
      command: >-
        {{ engine }} ps -q
        --filter "name=^/{{ clustered_instance_name }}$"
        --filter "status=running"
      become: yes
      changed_when: false
      register: docker_ps
      failed_when: docker_ps.rc != 0

    - name: Assert that the container is running
      assert:
        that: docker_ps.stdout != ''
        fail_msg: "The {{ clustered_instance_name }} is NOT running!"
