---
- name: Target machines
  import_playbook: target_machines.yaml

- name: Augment the inventory
  import_playbook: augment_inventory.yaml

- name: Setup localhost for s3
  hosts: localhost
  tasks:
    - name: Setup S3 storage connection
      include_role:
        name: pure_connection_setup
      vars:
        pure_s3_users: "{{ pure_usernames.split(',') | map('trim') | list }}"

- name: IRIS validation on the target machine
  hosts: target_machines
  tasks:
    - name: Find cluster that contains the current host
      set_fact:
        cluster_name: "{{ item.key }}"
      loop: "{{ machine_clusters | dict2items }}"
      when: inventory_hostname in item.value.machines

    - name: Check keepalived
      include_role:
        name: cluster_health_checks
        tasks_from: check_keepalived.yml
      when: inventory_hostname not in ((skip_keepalived_hosts | default('')).split(',') | map('trim') | list)

    - name: Check VIPs
      include_role:
        name: cluster_health_checks
        tasks_from: check_vips.yml

    - name: Check VIP drift
      include_role:
        name: cluster_health_checks
        tasks_from: check_vip_drift.yml

- name: IRIS validation on the instances
  hosts: individual_instances
  tasks:
    - name: Set container engine
      include_role:
        name: container_runner
        tasks_from: define_engine.yml

    - name: Check if container is running
      command: >-
        {{ engine }} ps -q
        --filter "name=^/iris_{{ clustered_instance_name }}_{{ machine_name }}$"
        --filter "status=running"
      become: yes
      changed_when: false
      register: docker_ps
      failed_when: docker_ps.rc != 0

    - name: Assert that the container is running
      assert:
        that: docker_ps.stdout != ''
        fail_msg: "The iris_{{ clustered_instance_name }}_{{ machine_name }} is NOT running!"
