---
- name: Load machine clusters
  hosts: localhost
  strategy: linear  # we use run_once
  gather_facts: no
  force_handlers: yes
  tasks:
    - name: Print iris_data_dir
      debug:
        msg: "iris_data_dir is {{ iris_data_dir }}"

    - name: Load machine clusters
      vars:
        content: >-
          {{ lookup('file', fname) | from_yaml }}
      set_fact:
        all_machine_clusters: >-
          {{ all_machine_clusters | default({}) | combine(content) }}
      loop: "{{ lookup('fileglob', iris_data_dir ~ '/machine_clusters/*.y*ml', wantlist=True) }}"
      loop_control:
        loop_var: fname

    - name: Distribute machine clusters info to machines
      set_fact:
        machine_clusters: >-
          {{
            all_machine_clusters
            | dict2items
            | selectattr('value.machines', 'contains', item)
            | items2dict
          }}
      delegate_to: "{{ item }}"
      delegate_facts: yes
      loop: "{{ groups['machines'] }}"
