---
- name: Load ACLs
  hosts: clustered_instances
  strategy: linear  # we use run_once
  gather_facts: no
  force_handlers: yes
  tasks:
    - name: Load common ACLs
      vars:
        fname: common.yaml
        read: >-
          {{ lookup('file', iris_data_dir ~ '/acls/' ~ fname) | from_yaml }}
        labelled: >-
          {{
            read.keys()
            | zip(read.values() | map('combine', {'fname': fname}))
            | items2dict(key_name=0, value_name=1)
          }}
      set_fact:
        common_acls: "{{ labelled }}"
      run_once: yes

    - name: Load clustered instance ACLs
      vars:
        fname: "{{ inventory_hostname }}.yaml"
        read: >-
          {{ lookup('file', iris_data_dir ~ '/acls/' ~ fname) | from_yaml }}
        labelled: >-
          {{
            read.keys()
            | zip(read.values() | map('combine', {'fname': fname}))
            | items2dict(key_name=0, value_name=1)
          }}
      set_fact:
        acls: >-
          {{ common_acls | combine(labelled) }}
