---
- name: Load static backends
  hosts: localhost
  strategy: free
  gather_facts: no
  force_handlers: yes
  tasks:
    - name: Load static backend configuration
      vars:
        content: >-
          {{ lookup('file', fname) | from_yaml }}
      set_fact:
        all_static_backends: >-
          {{ all_static_backends | default({}) | combine(content) }}
      loop: "{{ lookup('fileglob', '../data/static_backends/*.y*ml', wantlist=True) }}"
      loop_control:
        loop_var: fname

    - name: Distribute static backends to clustered instances
      set_fact:
        static_backends: >-
          {{ all_static_backends | dict2items
             | selectattr('value.clustered_instances', 'contains', item) | items2dict }}
      delegate_to: "{{ item }}"
      delegate_facts: yes
      loop: >-
        {{ all_static_backends | dict2items | map(attribute='value.clustered_instances') | flatten | unique }}
