---
- name: Load backends
  hosts: localhost
  strategy: free
  gather_facts: no
  force_handlers: yes
  tasks:
    - name: Load static backend configuration
      vars:
        content: >-
          {{ lookup('file', fname) | from_yaml }}
      set_fact:
        all_static_backends: >-
          {{ all_static_backends | default({}) | combine(content) }}
      loop: "{{ lookup('fileglob', '../backends/*.y*ml', wantlist=True) }}"
      loop_control:
        loop_var: fname

    - name: Distribute static backends to clusters
      set_fact:
        static_backends: >-
          {{ all_static_backends | dict2items | selectattr('value.clusters', 'contains', item) | items2dict }}
      delegate_to: "{{ item }}"
      delegate_facts: true
      with_items: >-
        {{ all_static_backends | dict2items | map(attribute='value.clusters') | flatten | unique }}
