---
- name: Set simulation facts
  hosts: target_machines
  gather_facts: no
  tasks:
    - name: Check for ambiguous simulation
      # Check for misleading values such as the strings "no" or "false" or "0".
      # To pass a false value from the command line, use -e"simulation=" or -e"{simulation: false}"
      assert:
        that: simulation | bool
        fail_msg: "Ambiguous non-boolean value for simulation {{ '%r' | format(simulation) }}"
        quiet: yes
      when: simulation

    - name: Set additional facts for simulating the machines
      set_fact:
        ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
        ansible_host: "172.24.0.{{ ansible_play_hosts_all.index(inventory_hostname) + 1 }}"
        pool: /mnt/storage/test_pool
        use_iso: false
        images_folder: "/mnt/storage"
        virgil_ssh_authorized_keys: >-
            {{ lookup('file', 'test_ssh_keys/id_rsa.pub') if simulation else '' }}
        simulation_proxy: "http://172.31.255.254:3128"
        cpu: 8
        ram: 32768
