---
- name: Prepare to target the machines
  hosts: machines
  gather_facts: no
  strategy: linear  # required by add_host which bypasses the host loop
  tasks:
    - name: Target machines
      vars:
        machine: "{{ hostvars[item] }}"
      add_host:
        name: "{{ item }}"
        groups: target_machines
        ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
      loop: "{{ ansible_play_hosts }}"
      when: target_dc | default('all') in [machine.dc, 'all']

- name: Prepare to target the machines
  hosts: target_machines
  gather_facts: no
  strategy: linear  # required by add_host which bypasses the host loop
  tasks:
    - name: Print machine info
      debug:
        var: hostvars[inventory_hostname]
