---
- name: Target machines
  import_playbook: target_machines.yaml

- name: Augment the inventory
  import_playbook: augment_inventory.yaml

- name: Check and teardown the instance
  hosts: target_machines
  gather_facts: yes
  tasks:
    - name: Get all containers
      include_role:
        name: container_runner
        tasks_from: get_container_list.yml
      vars:
        virgil_orchestrator: container runner  # TODO properly - "{{ machine.virgil_orchestrator }}"
        variable_name: container_list

    - name: Find the containers to be torn down
      set_fact:
        instances_to_be_deleted: >-
          {{ container_list | difference(instance_names)
          | select('match', reg_filter) | list }}
      vars:
        instance_names: >-
          {{ groups['individual_instances'] | default([])
          | map('regex_replace', '^', 'iris_') | list }}
        reg_filter: "^iris_.+_{{ inventory_hostname }}$"

    - name: Display the instances to be torn down
      debug:
        msg: "The following instances need to be deleted: {{ instances_to_be_deleted }}"

    - name: Tear down the instances
      include_role:
        name: container_runner
        tasks_from: rm_container.yml
      vars:
        virgil_orchestrator: container runner  # TODO properly - "{{ machine.virgil_orchestrator }}"
      loop: "{{ instances_to_be_deleted }}"
      loop_control:
        loop_var: name
      when:
        - instance_teardown_allowed | default(false)
        - instances_to_be_deleted | length > 0

    - name: Remove the instance folder
      file:
        state: absent
        path: "/mnt/data1/containers/{{ item }}"
      become: yes
      loop: "{{ instances_to_be_deleted }}"
      when:
        - instance_teardown_allowed | default(false)
        - instances_to_be_deleted | length > 0
