---
- name: Target machines
  import_playbook: target_machines.yaml

- name: Prepare simulation
  import_playbook: prepare_simulation.yaml

- name: Augment the inventory
  import_playbook: augment_inventory.yaml

- name: Create hypervisor group and config directory
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Add host to hypervisor group
      add_host:
        name: "{{ hypervisor | default('localhost') }}"
        groups: hypervisor
        ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
        images_folder: "/mnt/storage"

    - name: Create target directories
      file:
        dest: "{{ item }}"
        state: directory
        mode: u=rwx,go=rx
      loop:
        - "../generated_configs"
        - "../generated_configs/{{ target_dc }}"
      become: "{{ 'no' if use_cicd_pool | default(false) else 'yes' }}"

- name: Configure hypervisor
  hosts: hypervisor
  tasks:
    - name: Install awscli
      include_role:
        name: pure_connection_setup
        tasks_from: install.yml

    - name: Setup S3 storage connection
      include_role:
        name: pure_connection_setup
      vars:
        proxy_host: "192.168.255.254"
        proxy_port: "3128"
        pure_s3_users: "{{ pure_usernames.split(',') | map('trim') | list }}"

- name: Deploy simulated machines
  hosts: target_machines
  gather_facts: no
  tasks:
    - name: Set additional facts
      vars:
        os_codename:
          ubuntu2204: jammy
          ubuntu2404: noble
          rhel9: plow
      set_fact:
        virgil_ip_oob_dante: "{{ ansible_host }}"
        virgil_os_name: "{{ os }}"
        virgil_ip_dante: "{{ ansible_host }}"
        virgil_orchestrator: container runner  # TODO properly - "{{ machine.virgil_orchestrator }}"
        virgil_os_codename: "{{ os_codename[os] }}"
        virgil_os_version: "{{ os }}"

    - name: Set images for simulation OS
      vars:
        os_image:
          ubuntu2204: "{{ ubuntu2204_hypervisor_image }}"
          ubuntu2404: "{{ ubuntu2404_hypervisor_image }}"
          rhel9: "{{ rhel9_hypervisor_image }}"
      set_fact:
        image: "{{ images_folder }}/{{ os_image[virgil_os_name] }}"
        virgil_os_variant: "{{ os_variant }}"

    - name: Deploy test machines
      include_role:
        name: deploy_test_machines
        apply:
          delegate_to: "{{ groups['hypervisor'][0] }}"

    - name: Actually wait 600 seconds for nodes to come up
      # TODO clarify why this doesn't happen within the `deploy_test_machines` role
      wait_for_connection:
        connect_timeout: 5
        timeout: 600

- name: Deploy haproxy on simulated machines
  import_playbook: deploy_haproxy.yml
  vars:
    enable_dump_configs: true

# This playbook outputs a large amount of logs, exceeding the stdout limit of Azure Pipelines.
# Commenting out this role for now, until we can automate the necessary checks.
# Btw, we've already checked if the containers can run in deploy_haproxy.yml.
# - name: Check haproxy
#   import_playbook: check_haproxy.yml
